import type { HomeSectionConfig, HomeSectionKind } from '@/lib/customerPageHomeSectionCatalog'

export type HomeSectionPreset = {
  id: string
  kind: HomeSectionKind
  label: string
  description: string
  tags: string[]
  /** 미리보기 그라데이션 from */
  previewFrom: string
  /** 미리보기 그라데이션 to */
  previewTo: string
  config: HomeSectionConfig
}

const cardBindingsDefault: HomeSectionConfig['cardFieldBindings'] = {
  title: 'customerNameKo',
  description: 'summaryKo',
  price: 'adultBasePrice',
  location: 'departureCityKo',
}

const cardBindingsEn: HomeSectionConfig['cardFieldBindings'] = {
  title: 'customerNameEn',
  description: 'summaryEn',
  price: 'adultBasePrice',
  location: 'departureCityEn',
}

export const HOME_SECTION_PRESETS: HomeSectionPreset[] = [
  // —— 히어로 ——
  {
    id: 'hero-classic-center',
    kind: 'hero',
    label: '클래식 중앙',
    description: '브랜드 블루 · 중앙 타이틀 + CTA',
    tags: ['기본', '올인원'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: { structureVariant: 'centered-classic', uiPresetId: 'default' },
  },
  {
    id: 'hero-editorial-split',
    kind: 'hero',
    label: '에디토리얼 2단',
    description: '좌 텍스트 · 우 비주얼 매거진형',
    tags: ['에디토리얼', '2025'],
    previewFrom: '#334155',
    previewTo: '#0f172a',
    config: { structureVariant: 'split-editorial', uiPresetId: 'light-minimal' },
  },
  {
    id: 'hero-full-immersive-dark',
    kind: 'hero',
    label: '풀스크린 다크',
    description: '하단 CTA · 프리미엄 다크 톤',
    tags: ['럭셔리', '임팩트'],
    previewFrom: '#1e293b',
    previewTo: '#0f172a',
    config: { structureVariant: 'full-immersive', uiPresetId: 'premium-dark' },
  },
  {
    id: 'hero-left-minimal',
    kind: 'hero',
    label: '좌측 미니멀',
    description: '깔끔한 라이트 · 텍스트 중심',
    tags: ['미니멀', 'B2B'],
    previewFrom: '#f8fafc',
    previewTo: '#e2e8f0',
    config: { structureVariant: 'left-minimal', uiPresetId: 'light-minimal' },
  },
  {
    id: 'hero-compact-gold',
    kind: 'hero',
    label: '컴팩트 전환 바',
    description: '얇은 바 + 골드 CTA · 예약 집중',
    tags: ['전환', '골드'],
    previewFrom: '#1e3a5f',
    previewTo: '#0f172a',
    config: { structureVariant: 'compact-bar', uiPresetId: 'gold-accent' },
  },
  {
    id: 'hero-ocean-immersive',
    kind: 'hero',
    label: '오션 이머시브',
    description: '풀스크린 + 오션 그라데이션',
    tags: ['어드벤처', '감성'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: { structureVariant: 'full-immersive', uiPresetId: 'ocean-breeze' },
  },

  // —— 카테고리 ——
  {
    id: 'cat-icon-grid',
    kind: 'categories',
    label: '아이콘 6열',
    description: '클래식 카테고리 그리드',
    tags: ['기본', '탐색'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: { structureVariant: 'grid-icons', uiPresetId: 'default' },
  },
  {
    id: 'cat-horizontal-scroll',
    kind: 'categories',
    label: '가로 스크롤 칩',
    description: '모바일 친화 · 스와이프 탐색',
    tags: ['모바일', '트렌드'],
    previewFrom: '#f1f5f9',
    previewTo: '#e2e8f0',
    config: { structureVariant: 'horizontal-scroll', uiPresetId: 'light-minimal' },
  },
  {
    id: 'cat-bento',
    kind: 'categories',
    label: '벤토 디스커버리',
    description: '비대칭 벤토 · Pinterest형',
    tags: ['벤토', '2025'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: { structureVariant: 'bento-asymmetric', uiPresetId: 'ocean-breeze' },
  },
  {
    id: 'cat-large-tiles',
    kind: 'categories',
    label: '대형 비주얼 타일',
    description: '큰 썸네일 · 감성 어드벤처',
    tags: ['비주얼', '어드벤처'],
    previewFrom: '#ea580c',
    previewTo: '#9a3412',
    config: { structureVariant: 'large-tiles', uiPresetId: 'desert-sunset' },
  },
  {
    id: 'cat-compact-pills',
    kind: 'categories',
    label: '필 태그',
    description: '가벼운 태그 필 · 빠른 필터',
    tags: ['미니멀', '필터'],
    previewFrom: '#f8fafc',
    previewTo: '#cbd5e1',
    config: { structureVariant: 'compact-pills', uiPresetId: 'default' },
  },
  {
    id: 'cat-forest-grid',
    kind: 'categories',
    label: '포레스트 그리드',
    description: '자연·힐링 톤 아이콘 그리드',
    tags: ['자연', '힐링'],
    previewFrom: '#166534',
    previewTo: '#14532d',
    config: { structureVariant: 'grid-icons', uiPresetId: 'forest-retreat' },
  },

  // —— 신뢰 지표 ——
  {
    id: 'stats-grid-four',
    kind: 'stats',
    label: '4열 신뢰 수치',
    description: '고객·투어·평점 4칸',
    tags: ['기본', '신뢰'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: { structureVariant: 'grid-four', uiPresetId: 'default' },
  },
  {
    id: 'stats-highlight-band',
    kind: 'stats',
    label: '강조 밴드',
    description: '풀폭 밴드 · 소셜 프루프',
    tags: ['강조', 'B2C'],
    previewFrom: '#1e3a5f',
    previewTo: '#0f172a',
    config: { structureVariant: 'highlight-band', uiPresetId: 'gold-accent' },
  },
  {
    id: 'stats-card-row',
    kind: 'stats',
    label: '카드형 지표',
    description: '개별 카드 · 프리미엄 다크',
    tags: ['카드', '다크'],
    previewFrom: '#1e293b',
    previewTo: '#0f172a',
    config: { structureVariant: 'card-row', uiPresetId: 'premium-dark' },
  },
  {
    id: 'stats-inline-strip',
    kind: 'stats',
    label: '인라인 스트립',
    description: '한 줄 요약 · 미니멀',
    tags: ['미니멀', '컴팩트'],
    previewFrom: '#f8fafc',
    previewTo: '#e2e8f0',
    config: { structureVariant: 'inline-strip', uiPresetId: 'light-minimal' },
  },
  {
    id: 'stats-ocean-band',
    kind: 'stats',
    label: '오션 밴드',
    description: '오션 톤 강조 스트립',
    tags: ['오션', '밴드'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: { structureVariant: 'highlight-band', uiPresetId: 'ocean-breeze' },
  },

  // —— 카드 목록 ——
  {
    id: 'cards-popular-3',
    kind: 'card-list',
    label: '인기 투어 3열',
    description: '즐겨찾기 · 3열 그리드',
    tags: ['인기', '기본'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: {
      structureVariant: 'grid-three',
      uiPresetId: 'default',
      cardCount: 3,
      productQuery: 'favorites',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-luxury-2',
    kind: 'card-list',
    label: '럭셔리 2열 대형',
    description: '대형 카드 4개 · 골드 톤',
    tags: ['럭셔리', '대형'],
    previewFrom: '#1e3a5f',
    previewTo: '#0f172a',
    config: {
      structureVariant: 'grid-two-large',
      uiPresetId: 'gold-accent',
      cardCount: 4,
      productQuery: 'favorites',
      title: 'Premium Tours',
      cardFieldBindings: { ...cardBindingsEn },
    },
  },
  {
    id: 'cards-scroll-6',
    kind: 'card-list',
    label: '가로 스크롤 6개',
    description: '스와이프 카드 · 모바일 최적',
    tags: ['스크롤', '모바일'],
    previewFrom: '#f1f5f9',
    previewTo: '#cbd5e1',
    config: {
      structureVariant: 'horizontal-scroll',
      uiPresetId: 'light-minimal',
      cardCount: 6,
      productQuery: 'favorites',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-featured-grid',
    kind: 'card-list',
    label: '피처드 + 그리드',
    description: '1번째 대형 + 나머지 그리드',
    tags: ['피처드', '매거진'],
    previewFrom: '#334155',
    previewTo: '#0f172a',
    config: {
      structureVariant: 'featured-plus-grid',
      uiPresetId: 'premium-dark',
      cardCount: 5,
      productQuery: 'favorites',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-stacked-list',
    kind: 'card-list',
    label: '리스트형 4개',
    description: '가로형 리스트 · 비교하기 좋음',
    tags: ['리스트', '비교'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: {
      structureVariant: 'stacked-list',
      uiPresetId: 'default',
      cardCount: 4,
      productQuery: 'favorites',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-recent-6',
    kind: 'card-list',
    label: '최신 투어 6개',
    description: '최근 등록 상품 · 3열',
    tags: ['최신', '신규'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: {
      structureVariant: 'grid-three',
      uiPresetId: 'ocean-breeze',
      cardCount: 6,
      productQuery: 'recent',
      title: 'New Arrivals',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-desert-showcase',
    kind: 'card-list',
    label: '사막 쇼케이스',
    description: '2열 대형 · 선셋 감성',
    tags: ['어드벤처', '감성'],
    previewFrom: '#ea580c',
    previewTo: '#9a3412',
    config: {
      structureVariant: 'grid-two-large',
      uiPresetId: 'desert-sunset',
      cardCount: 2,
      productQuery: 'favorites',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },
  {
    id: 'cards-tag-grandcanyon',
    kind: 'card-list',
    label: '그랜드캐년 큐레이션',
    description: '태그 필터 · 가로 스크롤',
    tags: ['태그', '큐레이션'],
    previewFrom: '#166534',
    previewTo: '#14532d',
    config: {
      structureVariant: 'horizontal-scroll',
      uiPresetId: 'forest-retreat',
      cardCount: 4,
      productQuery: 'tag',
      tagFilter: '그랜드캐년',
      title: 'Grand Canyon Picks',
      cardFieldBindings: { ...cardBindingsEn },
    },
  },
  {
    id: 'cards-all-8',
    kind: 'card-list',
    label: '전체 투어 8개',
    description: '활성 상품 · 피처드 그리드',
    tags: ['전체', '카탈로그'],
    previewFrom: '#f8fafc',
    previewTo: '#94a3b8',
    config: {
      structureVariant: 'featured-plus-grid',
      uiPresetId: 'light-minimal',
      cardCount: 8,
      productQuery: 'all',
      cardFieldBindings: { ...cardBindingsDefault },
    },
  },

  // —— 서비스 강점 ——
  {
    id: 'feat-two-column',
    kind: 'features',
    label: '2열 텍스트',
    description: '아이콘 + 설명 클래식',
    tags: ['기본', '신뢰'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: { structureVariant: 'grid-two-text', uiPresetId: 'default' },
  },
  {
    id: 'feat-four-cards',
    kind: 'features',
    label: '4카드 그리드',
    description: '균형 잡힌 4칸 카드',
    tags: ['카드', '균형'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: { structureVariant: 'card-grid-four', uiPresetId: 'ocean-breeze' },
  },
  {
    id: 'feat-zigzag',
    kind: 'features',
    label: '지그재그 스토리',
    description: '좌우 교차 · 스토리텔링',
    tags: ['스토리', '2025'],
    previewFrom: '#ea580c',
    previewTo: '#9a3412',
    config: { structureVariant: 'alternating-rows', uiPresetId: 'desert-sunset' },
  },
  {
    id: 'feat-icon-row',
    kind: 'features',
    label: '아이콘 한 줄',
    description: '컴팩트 4아이콘 · 미니멀',
    tags: ['미니멀', '컴팩트'],
    previewFrom: '#f8fafc',
    previewTo: '#e2e8f0',
    config: { structureVariant: 'icon-row', uiPresetId: 'light-minimal' },
  },
  {
    id: 'feat-dark-cards',
    kind: 'features',
    label: '다크 4카드',
    description: '프리미엄 다크 · 고급 브랜드',
    tags: ['다크', '프리미엄'],
    previewFrom: '#1e293b',
    previewTo: '#0f172a',
    config: { structureVariant: 'card-grid-four', uiPresetId: 'premium-dark' },
  },
  {
    id: 'feat-forest-text',
    kind: 'features',
    label: '포레스트 2열',
    description: '자연 힐링 톤 · 2열 텍스트',
    tags: ['자연', '힐링'],
    previewFrom: '#166534',
    previewTo: '#14532d',
    config: { structureVariant: 'grid-two-text', uiPresetId: 'forest-retreat' },
  },

  // —— CTA ——
  {
    id: 'cta-centered',
    kind: 'cta',
    label: '중앙 CTA',
    description: '클래식 중앙 · 2버튼',
    tags: ['기본', '예약'],
    previewFrom: '#2563eb',
    previewTo: '#1e40af',
    config: { structureVariant: 'centered-classic', uiPresetId: 'default' },
  },
  {
    id: 'cta-full-band-gold',
    kind: 'cta',
    label: '골드 풀 밴드',
    description: '풀폭 밴드 · 프리미엄 전환',
    tags: ['전환', '골드'],
    previewFrom: '#1e3a5f',
    previewTo: '#0f172a',
    config: { structureVariant: 'full-band', uiPresetId: 'gold-accent' },
  },
  {
    id: 'cta-split-actions',
    kind: 'cta',
    label: '좌우 분할 CTA',
    description: '텍스트 좌 · 버튼 우',
    tags: ['분할', 'B2B'],
    previewFrom: '#334155',
    previewTo: '#1e293b',
    config: { structureVariant: 'split-actions', uiPresetId: 'light-minimal' },
  },
  {
    id: 'cta-inline-minimal',
    kind: 'cta',
    label: '인라인 미니멀',
    description: '한 줄 CTA · 가벼운 마무리',
    tags: ['미니멀', '푸터'],
    previewFrom: '#f8fafc',
    previewTo: '#cbd5e1',
    config: { structureVariant: 'inline-minimal', uiPresetId: 'light-minimal' },
  },
  {
    id: 'cta-dark-band',
    kind: 'cta',
    label: '다크 풀 밴드',
    description: '다크 프리미엄 · 강한 마감',
    tags: ['다크', '럭셔리'],
    previewFrom: '#1e293b',
    previewTo: '#0f172a',
    config: { structureVariant: 'full-band', uiPresetId: 'premium-dark' },
  },
  {
    id: 'cta-ocean-split',
    kind: 'cta',
    label: '오션 분할',
    description: '오션 톤 · 좌우 분할',
    tags: ['오션', '여행'],
    previewFrom: '#0e7490',
    previewTo: '#0369a1',
    config: { structureVariant: 'split-actions', uiPresetId: 'ocean-breeze' },
  },

  // —— 고객 후기 ——
  {
    id: 'reviews-card-grid',
    kind: 'reviews',
    label: '후기 카드 3열',
    description: '별점 + 인용문 그리드',
    tags: ['신뢰', '전환'],
    previewFrom: '#f59e0b',
    previewTo: '#d97706',
    config: { structureVariant: 'card-grid', uiPresetId: 'default', itemCount: 3 },
  },
  {
    id: 'reviews-carousel',
    kind: 'reviews',
    label: '후기 스크롤',
    description: '가로 스크롤 카드',
    tags: ['모바일', '스와이프'],
    previewFrom: '#6366f1',
    previewTo: '#4f46e5',
    config: { structureVariant: 'carousel-strip', uiPresetId: 'default', itemCount: 4 },
  },
  {
    id: 'reviews-featured',
    kind: 'reviews',
    label: '대형 인용',
    description: '하이라이트 후기 1건',
    tags: ['임팩트', '프리미엄'],
    previewFrom: '#334155',
    previewTo: '#1e293b',
    config: { structureVariant: 'featured-quote', uiPresetId: 'premium-dark', itemCount: 1 },
  },
  {
    id: 'reviews-masonry',
    kind: 'reviews',
    label: '믹스 masonry',
    description: '다양한 높이 카드',
    tags: ['에디토리얼'],
    previewFrom: '#ec4899',
    previewTo: '#db2777',
    config: { structureVariant: 'masonry-mix', uiPresetId: 'default', itemCount: 4 },
  },

  // —— FAQ ——
  {
    id: 'faq-accordion',
    kind: 'faq',
    label: 'FAQ 아코디언',
    description: '중앙 정렬 Q&A',
    tags: ['기본', '신뢰'],
    previewFrom: '#64748b',
    previewTo: '#475569',
    config: { structureVariant: 'accordion', uiPresetId: 'default', itemCount: 5 },
  },
  {
    id: 'faq-two-column',
    kind: 'faq',
    label: 'FAQ 2열',
    description: '질문을 좌우 분할',
    tags: ['정보', '밀도'],
    previewFrom: '#0d9488',
    previewTo: '#0f766e',
    config: { structureVariant: 'two-column', uiPresetId: 'ocean-breeze', itemCount: 6 },
  },
  {
    id: 'faq-compact',
    kind: 'faq',
    label: '컴팩트 FAQ',
    description: '좁은 폭 리스트',
    tags: ['미니멀'],
    previewFrom: '#94a3b8',
    previewTo: '#64748b',
    config: { structureVariant: 'compact-list', uiPresetId: 'light-minimal', itemCount: 4 },
  },

  // —— 갤러리 ——
  {
    id: 'gallery-grid-four',
    kind: 'gallery',
    label: '4열 갤러리',
    description: '균일 그리드 6장',
    tags: ['비주얼', '기본'],
    previewFrom: '#38bdf8',
    previewTo: '#0284c7',
    config: { structureVariant: 'grid-four', uiPresetId: 'default', itemCount: 6 },
  },
  {
    id: 'gallery-masonry',
    kind: 'gallery',
    label: '메이슨리',
    description: '높이 혼합 그리드',
    tags: ['에디토리얼'],
    previewFrom: '#a855f7',
    previewTo: '#7c3aed',
    config: { structureVariant: 'masonry', uiPresetId: 'default', itemCount: 8 },
  },
  {
    id: 'gallery-scroll',
    kind: 'gallery',
    label: '가로 스크롤',
    description: '스와이프 갤러리',
    tags: ['모바일'],
    previewFrom: '#f97316',
    previewTo: '#ea580c',
    config: { structureVariant: 'horizontal-scroll', uiPresetId: 'default', itemCount: 6 },
  },
  {
    id: 'gallery-featured',
    kind: 'gallery',
    label: '대형+그리드',
    description: '히어로 이미지 + 썸네일',
    tags: ['임팩트'],
    previewFrom: '#059669',
    previewTo: '#047857',
    config: { structureVariant: 'featured-plus-grid', uiPresetId: 'default', itemCount: 5 },
  },

  // —— 파트너 로고 ——
  {
    id: 'logos-scroll',
    kind: 'logos',
    label: '로고 스크롤',
    description: '가로 파트너 로고',
    tags: ['신뢰'],
    previewFrom: '#cbd5e1',
    previewTo: '#94a3b8',
    config: { structureVariant: 'row-scroll', uiPresetId: 'light-minimal', itemCount: 6 },
  },
  {
    id: 'logos-grid',
    kind: 'logos',
    label: '6열 그리드',
    description: '균일 로고 배치',
    tags: ['B2B'],
    previewFrom: '#e2e8f0',
    previewTo: '#cbd5e1',
    config: { structureVariant: 'grid-six', uiPresetId: 'default', itemCount: 6 },
  },
  {
    id: 'logos-strip',
    kind: 'logos',
    label: '뮤트 스트립',
    description: '얇은 신뢰 밴드',
    tags: ['미니멀'],
    previewFrom: '#f1f5f9',
    previewTo: '#e2e8f0',
    config: { structureVariant: 'muted-strip', uiPresetId: 'light-minimal', itemCount: 5 },
  },

  // —— 영상 ——
  {
    id: 'video-centered',
    kind: 'video',
    label: '중앙 영상',
    description: '제목 + 플레이어',
    tags: ['소개', '기본'],
    previewFrom: '#1e293b',
    previewTo: '#0f172a',
    config: { structureVariant: 'centered', uiPresetId: 'premium-dark' },
  },
  {
    id: 'video-split',
    kind: 'video',
    label: '텍스트 분할',
    description: '좌 설명 · 우 영상',
    tags: ['에디토리얼'],
    previewFrom: '#334155',
    previewTo: '#1e293b',
    config: { structureVariant: 'split-text', uiPresetId: 'default' },
  },
  {
    id: 'video-full',
    kind: 'video',
    label: '풀 너비',
    description: '와이드 시네마틱',
    tags: ['임팩트'],
    previewFrom: '#0f172a',
    previewTo: '#020617',
    config: { structureVariant: 'full-width', uiPresetId: 'premium-dark' },
  },

  // —— 뉴스레터 ——
  {
    id: 'newsletter-centered',
    kind: 'newsletter',
    label: '중앙 구독',
    description: '이메일 폼 중앙',
    tags: ['리드', '기본'],
    previewFrom: '#2563eb',
    previewTo: '#1d4ed8',
    config: { structureVariant: 'centered', uiPresetId: 'default' },
  },
  {
    id: 'newsletter-split',
    kind: 'newsletter',
    label: '2단 구독',
    description: '비주얼 + 폼',
    tags: ['프리미엄'],
    previewFrom: '#4f46e5',
    previewTo: '#4338ca',
    config: { structureVariant: 'split-image', uiPresetId: 'default' },
  },
  {
    id: 'newsletter-inline',
    kind: 'newsletter',
    label: '인라인 바',
    description: '한 줄 구독 CTA',
    tags: ['컴팩트'],
    previewFrom: '#64748b',
    previewTo: '#475569',
    config: { structureVariant: 'inline-bar', uiPresetId: 'light-minimal' },
  },

  // —— 프로모 ——
  {
    id: 'promo-full-band',
    kind: 'promo',
    label: '풀 밴드 프로모',
    description: '강조 배너 + CTA',
    tags: ['할인', '전환'],
    previewFrom: '#dc2626',
    previewTo: '#b91c1c',
    config: { structureVariant: 'full-band', uiPresetId: 'default' },
  },
  {
    id: 'promo-split',
    kind: 'promo',
    label: '분할 프로모',
    description: '좌 텍스트 · 우 버튼',
    tags: ['이벤트'],
    previewFrom: '#ea580c',
    previewTo: '#c2410c',
    config: { structureVariant: 'split-cta', uiPresetId: 'default' },
  },
  {
    id: 'promo-countdown',
    kind: 'promo',
    label: '카운트다운형',
    description: '한정 기간 강조',
    tags: ['긴급'],
    previewFrom: '#7c2d12',
    previewTo: '#431407',
    config: { structureVariant: 'countdown-style', uiPresetId: 'premium-dark' },
  },

  // —— 콘텐츠 블록 ——
  {
    id: 'richtext-prose',
    kind: 'rich-text',
    label: '중앙 본문',
    description: '제목 + 설명 텍스트',
    tags: ['스토리', '기본'],
    previewFrom: '#78716c',
    previewTo: '#57534e',
    config: { structureVariant: 'centered-prose', uiPresetId: 'default' },
  },
  {
    id: 'richtext-split',
    kind: 'rich-text',
    label: '미디어 분할',
    description: '이미지 + 본문',
    tags: ['에디토리얼'],
    previewFrom: '#6b7280',
    previewTo: '#4b5563',
    config: { structureVariant: 'split-media', uiPresetId: 'light-minimal' },
  },
  {
    id: 'richtext-box',
    kind: 'rich-text',
    label: '강조 박스',
    description: '카드형 콘텐츠',
    tags: ['정보'],
    previewFrom: '#a8a29e',
    previewTo: '#78716c',
    config: { structureVariant: 'highlight-box', uiPresetId: 'default' },
  },
]

export const HOME_SECTION_KIND_FILTER_OPTIONS: Array<{
  id: 'all' | HomeSectionKind
  label: string
}> = [
  { id: 'all', label: '전체' },
  { id: 'hero', label: '히어로' },
  { id: 'card-list', label: '카드 목록' },
  { id: 'categories', label: '카테고리' },
  { id: 'stats', label: '신뢰 지표' },
  { id: 'features', label: '강점' },
  { id: 'cta', label: 'CTA' },
  { id: 'reviews', label: '후기' },
  { id: 'faq', label: 'FAQ' },
  { id: 'gallery', label: '갤러리' },
  { id: 'logos', label: '로고' },
  { id: 'video', label: '영상' },
  { id: 'newsletter', label: '뉴스레터' },
  { id: 'promo', label: '프로모' },
  { id: 'rich-text', label: '콘텐츠' },
]

export function getHomeSectionPresetById(presetId: string): HomeSectionPreset | null {
  return HOME_SECTION_PRESETS.find((preset) => preset.id === presetId) ?? null
}

export function getHomeSectionPresetsByKind(kind: HomeSectionKind | 'all'): HomeSectionPreset[] {
  if (kind === 'all') return HOME_SECTION_PRESETS
  return HOME_SECTION_PRESETS.filter((preset) => preset.kind === kind)
}

export function applyHomeSectionPreset(preset: HomeSectionPreset): {
  kind: HomeSectionKind
  config: HomeSectionConfig
} {
  const config: HomeSectionConfig = { ...preset.config }
  if (preset.config.cardFieldBindings) {
    config.cardFieldBindings = { ...preset.config.cardFieldBindings }
  }
  return { kind: preset.kind, config }
}
