/** Office Schedule modal — always English regardless of app locale */
export const OFFICE_SCHEDULE_COPY = {
  title: 'Office Schedule',
  close: 'Close',
  hint: 'Select a staff member, then click or drag cells. Press Save to apply changes. Ctrl+Z to undo.',
  selectStaff: 'Select staff to schedule',
  showStaff: 'Show on grid',
  hideStaff: 'Hide from grid',
  eraser: 'Eraser',
  save: 'Save',
  saving: 'Saving...',
  saveSuccess: 'Schedule saved.',
  unsavedChanges: 'You have unsaved changes. Close anyway?',
  unsavedMonthChange: 'You have unsaved changes. Change month anyway?',
  timeStart: 'Start',
  timeEnd: 'End',
  legend: 'Color legend (click swatch to change)',
  comboHint: 'Overlap = split colors',
  statsTitle: 'Scheduled hours',
  statsTotal: 'Total',
  dailyTotalHours: 'Total hrs',
  dailyPay: 'Daily pay',
  statsWeek: 'This week',
  statsTwoWeeks: 'Last 2 weeks',
  statsMonth: 'Viewed month',
  statsPay: 'Pay',
  statsHours: '{h}h',
  resetColor: 'Reset color',
  undo: 'Undo',
  redo: 'Redo',
  history: 'History',
  historyTitle: 'Save history',
  historyDesc: 'Saved snapshots for {month}. Restore replaces the schedule in that date range.',
  historyEmpty: 'No saved revisions for this month yet.',
  historyLoadError: 'Could not load save history.',
  historyRestoreError: 'Failed to restore this revision.',
  historyRestore: 'Restore to this version',
  historyRestoreConfirm:
    'Restore the schedule to the version saved by {who} on {when}? Unsaved changes will be lost.',
  historyActionSave: 'Save',
  historyActionRestore: 'Restore',
  historyRange: 'Date range',
  historyChanges: 'Changes',
  historySlots: 'Slots in snapshot',
  historyRestoredFromPrior: 'Restored from a prior revision',
  historyRestoreRestricted: 'Only Office Manager / Super can restore.',
  prevMonth: 'Previous month',
  nextMonth: 'Next month',
  loadError: 'Could not load schedule.',
  saveError: 'Failed to save schedule.',
  noStaff: 'No active OP or Office Manager staff.',
  cellHint: 'Click or drag to schedule',
  readOnly: 'You can only edit your own schedule.',
  loading: 'Loading...',
} as const
