/** Office Schedule modal — always English regardless of app locale */
export const OFFICE_SCHEDULE_COPY = {
  title: 'Office Schedule',
  close: 'Close',
  hint: 'Select a staff member, then click or drag cells to schedule. Use the OFF row for mandatory rest days. Press Save to apply changes. Ctrl+Z to undo.',
  selectStaff: 'Select staff to schedule',
  staffPickerShow: 'Show staff picker',
  staffPickerHide: 'Hide staff picker',
  showStaff: 'Show on grid',
  hideStaff: 'Hide from grid',
  eraser: 'Eraser',
  save: 'Save',
  saving: 'Saving...',
  saveSuccess: 'Schedule saved.',
  unsavedChanges: 'You have unsaved changes. Close anyway?',
  unsavedMonthChange: 'You have unsaved changes. Change month anyway?',
  timeStart: 'Start',
  timeEnd: 'End',
  legend: 'Color legend (click swatch to change)',
  comboHint: 'Overlap = split colors',
  statsTitle: 'Scheduled hours',
  statsShow: 'Show scheduled hours',
  statsHide: 'Hide scheduled hours',
  statsTotal: 'Total',
  dailyTotalHours: 'Total hrs',
  dailyPay: 'Daily pay',
  statsWeek: 'This week',
  statsTwoWeeks: 'Last 2 weeks',
  statsFirstHalf: '1st–15th',
  statsSecondHalf: '16th–EOM',
  statsMonth: 'Viewed month',
  statsPay: 'Pay',
  statsHourlyRate: 'Hourly rate (today)',
  statsScheduledDays: 'Scheduled days',
  statsHours: '{h}h',
  resetColor: 'Reset color',
  undo: 'Undo',
  redo: 'Redo',
  history: 'History',
  historyTitle: 'Save history',
  historyDesc: 'Saved snapshots for {month}. Restore replaces the schedule in that date range.',
  historyEmpty: 'No saved revisions for this month yet.',
  historyLoadError: 'Could not load save history.',
  historyRestoreError: 'Failed to restore this revision.',
  historyRestore: 'Restore to this version',
  historyRestoreConfirm:
    'Restore the schedule to the version saved by {who} on {when}? Unsaved changes will be lost.',
  historyActionSave: 'Save',
  historyActionRestore: 'Restore',
  historyRange: 'Date range',
  historyChanges: 'Changes',
  historySlots: 'Slots in snapshot',
  historyRestoredFromPrior: 'Restored from a prior revision',
  historyRestoreRestricted: 'Only Office Manager / Super can restore.',
  prevMonth: 'Previous month',
  nextMonth: 'Next month',
  loadError: 'Could not load schedule.',
  saveError: 'Failed to save schedule.',
  noStaff: 'No active OP or Office Manager staff.',
  offRowLabel: 'OFF',
  offDayHint: 'Click or drag to mark mandatory day off for selected staff',
  offDayCellLabel: 'OFF',
  offDayScheduleBlocked:
    '{name} is marked OFF on {date}. Remove OFF from the OFF row before adding work hours.',
  cellHint: 'Click or drag to schedule',
  readOnly: 'You can only edit your own schedule.',
  loading: 'Loading...',
  employeeSettingsTitle: 'Employment & pay',
  employeeSettingsButton: 'Employment',
  employeeSettingsDesc:
    'Set hourly vs monthly pay, full-time vs part-time, and fixed weekly rest days for full-time staff (5-day week). Changes save automatically.',
  employeeSettingsStaff: 'Staff',
  employeeSettingsPayType: 'Pay type',
  employeeSettingsEmployment: 'Employment',
  employeeSettingsRestDays: 'Fixed rest days (full-time, 5-day week)',
  employeeSettingsHourly: 'Hourly',
  employeeSettingsMonthly: 'Monthly salary',
  employeeSettingsFullTime: 'Full-time',
  employeeSettingsPartTime: 'Part-time',
  employeeSettingsRestDaysNa: '—',
  employeeSettingsRestDayOff: 'Fixed rest day',
  employeeSettingsRestDayWork: 'Working day',
  employeeSettingsReadOnly: 'Only Office Manager / Super can edit employment settings.',
  employeeSettingsAutoSave: 'Changes save automatically.',
  employeeSettingsLoadError: 'Could not load employment settings.',
  employeeSettingsSaveError: 'Failed to save employment settings.',
  employeeSettingsMonthlyMin: 'Monthly minimum (8h/day)',
  statsPayTypeHourly: 'Hourly',
  statsPayTypeMonthly: 'Monthly',
  statsEmploymentFullTime: 'FT',
  statsEmploymentPartTime: 'PT',
  employeeSettingsBatchFirstHalf: '1st half',
  employeeSettingsBatchSecondHalf: '2nd half',
  employeeSettingsBatchFirstHalfTitle: 'Fill 1st half (from 12:00 PM, 8h) on all non-rest days this month',
  employeeSettingsBatchSecondHalfTitle: 'Fill 2nd half (from 4:00 PM, 8h) on all non-rest days this month',
  employeeSettingsBatchFillConfirm:
    'Add {shift} hours (from {time}, 8h/day) for {name} on all non-rest days in {month}? Existing slots are kept. Press Save to apply.',
  employeeSettingsBatchFillDone: 'Batch fill added to the grid. Press Save to store.',
  employeeSettingsBatchFillNone: 'All slots for this shift are already filled.',
  employeeSettingsBatchFillHint:
    'Batch fill applies to viewed month ({month}) on the schedule grid (Save required).',
} as const
