-- 임시 해결책: RLS 비활성화 (테스트용)
ALTER TABLE document_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_reminders DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_download_logs DISABLE ROW LEVEL SECURITY;
