'use client'

import { useState, useEffect } from 'react'
import { FileText, Mail, Download, Eye } from 'lucide-react'
import { generateTemplateContext } from '@/lib/templateContext'
import { renderTemplateString } from '@/lib/template'

interface SimpleDocumentGeneratorProps {
  reservationId: string
  customerName: string
  productName: string
  tourDate: string
  pickupTime: string
  pickupLocation: string
}

export default function SimpleDocumentGenerator({
  reservationId,
  customerName,
  productName,
  tourDate,
  pickupTime,
  pickupLocation
}: SimpleDocumentGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [previewDoc, setPreviewDoc] = useState<null | 'voucher' | 'pickup'>(null)
  const [previewLanguage, setPreviewLanguage] = useState<'ko' | 'en'>('ko')
  const [generatedContent, setGeneratedContent] = useState<{
    voucher: { ko: string; en: string }
    pickup: { ko: string; en: string }
  }>({ 
    voucher: { ko: '', en: '' }, 
    pickup: { ko: '', en: '' } 
  })
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [customerLanguage, setCustomerLanguage] = useState<'ko' | 'en'>('ko')

  // 컴포넌트 마운트 시 자동 생성
  useEffect(() => {
    if (reservationId && !autoGenerated) {
      autoGenerateDocuments()
    }
  }, [reservationId, autoGenerated])

  // 자동 문서 생성
  const autoGenerateDocuments = async () => {
    if (autoGenerated) return
    
    setGenerating(true)
    setAutoGenerated(true)
    
    try {
      // 먼저 고객 언어 확인
      await detectCustomerLanguage()
      
      // 투어 바우처와 픽업 안내를 한국어와 영어로 모두 생성
      await Promise.all([
        generateDocument('voucher', true, 'ko'),
        generateDocument('voucher', true, 'en'),
        generateDocument('pickup', true, 'ko'),
        generateDocument('pickup', true, 'en')
      ])
      
      console.log('다국어 문서 자동 생성 완료')
    } catch (error) {
      console.error('다국어 문서 자동 생성 오류:', error)
    } finally {
      setGenerating(false)
    }
  }

  // 고객 언어 감지
  const detectCustomerLanguage = async () => {
    try {
      const context = await generateTemplateContext(reservationId, 'ko')
      if (context?.customer?.language) {
        const lang = context.customer.language.toLowerCase()
        setCustomerLanguage(lang === 'en' ? 'en' : 'ko')
        console.log('고객 언어 감지:', lang === 'en' ? '영어' : '한국어')
      }
    } catch (error) {
      console.warn('고객 언어 감지 실패, 기본값 사용:', error)
      setCustomerLanguage('ko')
    }
  }

  // 간단한 템플릿들
  const templates = {
    voucher_ko: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #2563eb; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #2563eb; margin: 0;">🎫 투어 바우처</h1>
          <p style="color: #666; margin: 5px 0;">Tour Voucher</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">예약번호: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">예약 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">고객명:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">이메일:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.email}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">예약 상태:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.status}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">상품 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">상품명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_ko}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">영문명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_en}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">카테고리:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.category}} - {{product.sub_category}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 날짜:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 시간:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.tour_time}}</td>
            </tr>
          </table>
        </div>

        <!-- Tour Course 섹션 -->
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">🗺️ 투어 코스</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_course_info}}
          </div>
        </div>

        <!-- Tour Duration 섹션 -->
        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">⏰ 투어 시간</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">총 투어 시간:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 18px; font-weight: bold;">{{product.duration}}시간</td>
            </tr>
          </table>
        </div>

        <!-- Tour Schedule 섹션 -->
        <div style="background: #f3e8ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #7c3aed; margin-top: 0;">📅 투어 스케줄</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_schedule_customer_view}}
          </div>
        </div>

        <!-- Tour Information 섹션 -->
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">ℹ️ 투어 상세 정보</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_information_details}}
          </div>
        </div>

        <!-- Cancellation Policy 섹션 -->
        <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #dc2626; margin-top: 0;">📋 취소 정책</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{cancellation_policy}}
          </div>
        </div>

        <!-- Inclusions 섹션 -->
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">✅ 포함 사항 (INCLUSIONS)</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{inclusions}}
          </div>
        </div>

        <!-- Exclusions 섹션 -->
        <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #dc2626; margin-top: 0;">❌ 불포함 사항 (EXCLUSIONS)</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{exclusions}}
          </div>
        </div>

        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">픽업 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">픽업 시간:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 장소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.display}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 위치:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">주소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">투어 인원</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">성인:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.adults}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">아동:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.child}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">유아:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.infant}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">총 인원:</td>
              <td style="padding: 8px 0; color: #111827; font-weight: bold;">{{reservation.total_people}}명</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">📋 중요 안내사항</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li>투어 당일 픽업 시간 10분 전까지 픽업 장소에 도착해 주세요</li>
            <li>신분증을 지참해 주세요</li>
            <li>날씨에 따라 일정이 변경될 수 있습니다</li>
            <li>문의사항이 있으시면 연락주세요</li>
            <li>이 바우처를 투어 당일 가이드에게 제시해 주세요</li>
          </ul>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>감사합니다! 즐거운 투어 되세요! 🎉</p>
          <p style="margin: 5px 0; font-size: 12px;">문의: {{channel.name}}</p>
        </div>
      </div>
    `,
    
    voucher_en: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #2563eb; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #2563eb; margin: 0;">🎫 Tour Voucher</h1>
          <p style="color: #666; margin: 5px 0;">투어 바우처</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">Reservation No: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">Reservation Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Customer Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Contact:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Email:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.email}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Status:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.status}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">Tour Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Tour Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_en}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Korean Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_ko}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Category:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.category}} - {{product.sub_category}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Tour Date:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Tour Time:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.tour_time}}</td>
            </tr>
          </table>
        </div>

        <!-- Tour Course Section -->
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">🗺️ Tour Course</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_course_info}}
          </div>
        </div>

        <!-- Tour Duration Section -->
        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">⏰ Tour Duration</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Total Tour Duration:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 18px; font-weight: bold;">{{product.duration}} hours</td>
            </tr>
          </table>
        </div>

        <!-- Tour Schedule Section -->
        <div style="background: #f3e8ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #7c3aed; margin-top: 0;">📅 Tour Schedule</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_schedule_customer_view}}
          </div>
        </div>

        <!-- Tour Information Section -->
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">ℹ️ Tour Information</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{tour_information_details}}
          </div>
        </div>

        <!-- Cancellation Policy Section -->
        <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #dc2626; margin-top: 0;">📋 Cancellation Policy</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{cancellation_policy}}
          </div>
        </div>

        <!-- Inclusions Section -->
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">✅ Inclusions</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{inclusions}}
          </div>
        </div>

        <!-- Exclusions Section -->
        <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #dc2626; margin-top: 0;">❌ Exclusions</h2>
          <div style="color: #111827; line-height: 1.6;">
            {{exclusions}}
          </div>
        </div>

        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">Pickup Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Pickup Time:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Pickup Location:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.display}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Pickup Point:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Address:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">Tour Participants</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Adults:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.adults}} people</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Children:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.child}} people</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Infants:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.infant}} people</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Total:</td>
              <td style="padding: 8px 0; color: #111827; font-weight: bold;">{{reservation.total_people}} people</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">📋 Important Information</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li>Please arrive at the pickup location 10 minutes before the scheduled pickup time</li>
            <li>Please bring your ID card</li>
            <li>The schedule may change depending on weather conditions</li>
            <li>Please contact us if you have any questions</li>
            <li>Please present this voucher to your guide on the day of the tour</li>
          </ul>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>Thank you! Have a wonderful tour! 🎉</p>
          <p style="margin: 5px 0; font-size: 12px;">Contact: {{channel.name}}</p>
        </div>
      </div>
    `,
    
    pickup_ko: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #059669; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #059669; margin: 0;">🚌 픽업 안내</h1>
          <p style="color: #666; margin: 5px 0;">Pickup Information</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">예약번호: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">고객 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">고객명:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 날짜:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">상품명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_ko}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #dbeafe; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">📍 픽업 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">픽업 시간:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 20px; font-weight: bold; color: #dc2626;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 호텔:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.hotel_name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 위치:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">주소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">안내:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.description_ko}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">🚗 차량 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">차량 유형:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.type || '투어 버스'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">차량 번호:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.plate_number || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">운전사:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">👨‍🏫 가이드 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">가이드명:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">언어:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.language || '한국어'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">경험:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.experience || '풍부한 경험'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">⚠️ 중요 안내사항</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li><strong>픽업 시간 10분 전까지 도착해 주세요</strong></li>
            <li>버스는 정시에 출발합니다 (늦으실 경우 다음 픽업 장소로 이동)</li>
            <li>신분증을 지참해 주세요</li>
            <li>날씨에 따라 일정이 변경될 수 있습니다</li>
            <li>긴급상황 시 가이드 또는 운전사에게 연락주세요</li>
            <li>투어 바우처를 가이드에게 제시해 주세요</li>
          </ul>
        </div>

        <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #047857; margin-top: 0;">📞 연락처</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">가이드:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">운전사:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">고객센터:</td>
              <td style="padding: 8px 0; color: #111827;">{{channel.contact_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>안전하고 즐거운 투어 되세요! 🚌✨</p>
          <p style="margin: 5px 0; font-size: 12px;">문의: {{channel.name}}</p>
        </div>
      </div>
    `,
    
    pickup_en: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #059669; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #059669; margin: 0;">🚌 Pickup Information</h1>
          <p style="color: #666; margin: 5px 0;">픽업 안내</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">Reservation No: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">Customer Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Customer Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Contact:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Tour Date:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Tour Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_en}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #dbeafe; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">📍 Pickup Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Pickup Time:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 20px; font-weight: bold; color: #dc2626;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Pickup Hotel:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.hotel_name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Pickup Point:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Address:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Instructions:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.description_en}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">🚗 Vehicle Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Vehicle Type:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.type || 'Tour Bus'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">License Plate:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.plate_number || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Driver:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Driver Contact:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">👨‍🏫 Guide Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Guide Name:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Guide Contact:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Language:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.language || 'English'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Experience:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.experience || 'Experienced'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">⚠️ Important Information</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li><strong>Please arrive 10 minutes before the pickup time</strong></li>
            <li>The bus will depart on time (if late, please go to the next pickup location)</li>
            <li>Please bring your ID card</li>
            <li>The schedule may change depending on weather conditions</li>
            <li>In case of emergency, please contact the guide or driver</li>
            <li>Please present your tour voucher to the guide</li>
          </ul>
        </div>

        <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #047857; margin-top: 0;">📞 Contact Information</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">Guide:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Driver:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Customer Service:</td>
              <td style="padding: 8px 0; color: #111827;">{{channel.contact_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>Have a safe and wonderful tour! 🚌✨</p>
          <p style="margin: 5px 0; font-size: 12px;">Contact: {{channel.name}}</p>
        </div>
      </div>
    `
  }

  const generateDocument = async (type: 'voucher' | 'pickup', isAuto = false, language: 'ko' | 'en' = 'ko') => {
    if (!isAuto) {
      setGenerating(true)
    }
    
    try {
      console.log(`${type} 문서 생성 시작 (${language})...`)
      
      // 템플릿 컨텍스트 생성 (에러가 발생해도 기본 데이터 사용)
      let context = null
      try {
        context = await generateTemplateContext(reservationId, language)
        console.log('템플릿 컨텍스트 생성 완료:', context ? Object.keys(context) : 'null')
      } catch (error) {
        console.warn('템플릿 컨텍스트 생성 실패:', error)
        console.log('기본 컨텍스트 데이터 사용')
        // 기본 컨텍스트 데이터 제공
        context = {
          reservation: {
            id: reservationId,
            tour_date: tourDate,
            pickup_time: pickupTime,
            tour_time: '09:00',
            adults: 2,
            child: 0,
            infant: 0,
            total_people: 2,
            total_price: 100000,
            status: 'confirmed'
          },
          customer: {
            name: customerName || '고객',
            email: 'customer@example.com',
            phone: '010-0000-0000',
            language: language
          },
          product: {
            name_ko: productName || '투어 상품',
            name_en: 'Tour Product',
            category: '투어',
            sub_category: '일반',
            duration: 8
          },
          channel: {
            name: '일반 채널',
            type: 'direct',
            contact_phone: '02-0000-0000'
          },
          pickup: {
            display: pickupLocation || '기본 픽업 호텔',
            hotel_name: pickupLocation || '기본 픽업 호텔',
            pick_up_location: '호텔 로비',
            address: '서울시 강남구',
            description_ko: '호텔 로비에서 픽업',
            description_en: 'Pickup at hotel lobby'
          },
          vehicle: {
            type: '투어 버스',
            plate_number: 'TBD',
            driver_name: 'TBD',
            driver_phone: 'TBD'
          },
          guide: {
            name: 'TBD',
            phone: 'TBD',
            language: language === 'ko' ? '한국어' : 'English',
            experience: language === 'ko' ? '풍부한 경험' : 'Experienced'
          },
          // 새로운 섹션들 추가
          tour_course_info: language === 'ko' ? 
            '• 서울 시청\n• 경복궁\n• 인사동\n• 명동\n• 남산타워' : 
            '• Seoul City Hall\n• Gyeongbokgung Palace\n• Insadong\n• Myeongdong\n• N Seoul Tower',
          tour_schedule_customer_view: language === 'ko' ?
            '09:00 - 호텔 픽업\n10:00 - 경복궁 관람\n12:00 - 점심 식사\n14:00 - 인사동 쇼핑\n16:00 - 남산타워\n18:00 - 호텔 도착' :
            '09:00 - Hotel pickup\n10:00 - Gyeongbokgung Palace tour\n12:00 - Lunch\n14:00 - Insadong shopping\n16:00 - N Seoul Tower\n18:00 - Hotel arrival',
          tour_information_details: language === 'ko' ?
            '• 상품 설명: 서울의 주요 관광지를 둘러보는 하루 투어\n• 픽업/드롭 정보: 호텔에서 픽업 및 드롭오프\n• 수하물 정보: 개인 소지품만 가능\n• 투어 운영 정보: 전문 가이드와 함께 진행\n• 준비 사항: 편안한 신발과 간단한 개인 소지품\n• 소그룹 정보: 최대 15명 소그룹 투어\n• 안내사항: 날씨에 따라 일정이 변경될 수 있습니다' :
            '• Product Description: Full-day tour of Seoul\'s major attractions\n• Pickup/Drop Info: Hotel pickup and drop-off\n• Luggage Info: Personal belongings only\n• Tour Operation: Led by professional guide\n• Preparation: Comfortable shoes and personal items\n• Small Group: Maximum 15 people\n• Notice: Schedule may change due to weather',
          cancellation_policy: language === 'ko' ?
            '• 투어 3일 전: 100% 환불\n• 투어 1일 전: 50% 환불\n• 투어 당일: 환불 불가\n• 천재지변으로 인한 취소: 100% 환불' :
            '• 3 days before tour: 100% refund\n• 1 day before tour: 50% refund\n• On tour day: No refund\n• Cancellation due to natural disasters: 100% refund',
          inclusions: language === 'ko' ?
            '• 전문 가이드 서비스\n• 교통편 (왕복)\n• 모든 입장료\n• 점심 식사\n• 여행자 보험' :
            '• Professional guide service\n• Round-trip transportation\n• All entrance fees\n• Lunch\n• Travel insurance',
          exclusions: language === 'ko' ?
            '• 개인 경비\n• 숙박비\n• 항공료\n• 개인 보험\n• 기념품 및 쇼핑' :
            '• Personal expenses\n• Accommodation\n• Airfare\n• Personal insurance\n• Souvenirs and shopping'
        }
      }
      
      if (!context) {
        console.error('템플릿 컨텍스트 생성 실패')
        return
      }
      
      // 언어에 따른 템플릿 선택
      const templateKey = `${type}_${language}`
      const template = templates[templateKey as keyof typeof templates]
      
      if (!template) {
        console.error(`템플릿을 찾을 수 없습니다: ${templateKey}`)
        return
      }
      
      // 템플릿 렌더링
      const renderedContent = renderTemplateString(template, context)
      
      setGeneratedContent(prev => ({
        ...prev,
        [type]: {
          ...prev[type],
          [language]: renderedContent
        }
      }))
      
      console.log(`${type} 문서 생성 완료 (${language})`)
    } catch (error) {
      console.error(`${type} 문서 생성 오류 (${language}):`, error)
      // 오류 발생 시에도 기본 문서 생성
      const fallbackContext = {
        reservation: {
          id: reservationId,
          tour_date: tourDate,
          pickup_time: pickupTime,
          tour_time: '09:00',
          adults: 2,
          child: 0,
          infant: 0,
          total_people: 2,
          total_price: 100000,
          status: 'confirmed'
        },
        customer: {
          name: customerName || '고객',
          email: 'customer@example.com',
          phone: '010-0000-0000',
          language: language
        },
        product: {
          name_ko: productName || '투어 상품',
          name_en: 'Tour Product',
          category: '투어',
          sub_category: '일반'
        },
        channel: {
          name: '일반 채널',
          type: 'direct',
          contact_phone: '02-0000-0000'
        },
        pickup: {
          display: pickupLocation || '기본 픽업 호텔',
          hotel_name: pickupLocation || '기본 픽업 호텔',
          pick_up_location: '호텔 로비',
          address: '서울시 강남구',
          description_ko: '호텔 로비에서 픽업',
          description_en: 'Pickup at hotel lobby'
        },
        vehicle: {
          type: '투어 버스',
          plate_number: 'TBD',
          driver_name: 'TBD',
          driver_phone: 'TBD'
        },
        guide: {
          name: 'TBD',
          phone: 'TBD',
          language: language === 'ko' ? '한국어' : 'English',
          experience: language === 'ko' ? '풍부한 경험' : 'Experienced'
        }
      }
      
      const templateKey = `${type}_${language}`
      const template = templates[templateKey as keyof typeof templates]
      
      if (template) {
        const renderedContent = renderTemplateString(template, fallbackContext)
        setGeneratedContent(prev => ({
          ...prev,
          [type]: {
            ...prev[type],
            [language]: renderedContent
          }
        }))
      }
    } finally {
      if (!isAuto) {
        setGenerating(false)
      }
    }
  }

  const downloadDocument = (type: 'voucher' | 'pickup', language: 'ko' | 'en' = 'ko') => {
    const content = generatedContent[type][language]
    if (!content) return
    
    const blob = new Blob([content], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${type === 'voucher' ? '투어바우처' : '픽업안내'}_${language}_${customerName}_${tourDate}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const sendEmail = (type: 'voucher' | 'pickup', language: 'ko' | 'en' = 'ko') => {
    const content = generatedContent[type][language]
    if (!content) return
    
    const subject = type === 'voucher' 
      ? (language === 'ko' ? '투어 바우처' : 'Tour Voucher')
      : (language === 'ko' ? '픽업 안내' : 'Pickup Information')
    const body = encodeURIComponent(content)
    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${body}`
    window.open(mailtoLink)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-gray-900">📄 간편 문서 생성</h3>
          <p className="text-sm text-gray-600">
            고객 언어: <span className="font-medium">{customerLanguage === 'ko' ? '한국어' : 'English'}</span>
          </p>
        </div>
        {autoGenerated && (
          <div className="flex items-center gap-2 text-sm text-green-600">
            <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            다국어 자동 생성 완료
          </div>
        )}
      </div>
      
      {generating && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
            <span className="text-blue-700">문서를 자동 생성하고 있습니다...</span>
          </div>
        </div>
      )}
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* 투어 바우처 */}
        <div className="border rounded-lg p-4 bg-white">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-5 h-5 text-blue-600" />
            <h4 className="font-medium text-gray-900">투어 바우처</h4>
            {(generatedContent.voucher.ko || generatedContent.voucher.en) && (
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            )}
          </div>
          
          <div className="space-y-2">
            <div className="flex gap-2">
              <button
                onClick={() => generateDocument('voucher', false, 'ko')}
                disabled={generating}
                className="flex-1 px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 text-sm"
              >
                {generating ? '생성 중...' : '한국어 생성'}
              </button>
              <button
                onClick={() => generateDocument('voucher', false, 'en')}
                disabled={generating}
                className="flex-1 px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50 text-sm"
              >
                {generating ? '생성 중...' : 'English 생성'}
              </button>
            </div>
            
            {(generatedContent.voucher.ko || generatedContent.voucher.en) && (
              <div className="space-y-2">
                {/* 한국어 버전 */}
                {generatedContent.voucher.ko && (
                  <div className="border rounded p-2 bg-gray-50">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-700">🇰🇷 한국어</span>
                      <div className="flex gap-1">
                        <button
                          onClick={() => {
                            setPreviewDoc('voucher')
                            setPreviewLanguage('ko')
                          }}
                          className="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-xs flex items-center gap-1"
                        >
                          <Eye className="w-3 h-3" />
                          미리보기
                        </button>
                        <button
                          onClick={() => downloadDocument('voucher', 'ko')}
                          className="px-2 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200 text-xs flex items-center gap-1"
                        >
                          <Download className="w-3 h-3" />
                          다운로드
                        </button>
                        <button
                          onClick={() => sendEmail('voucher', 'ko')}
                          className="px-2 py-1 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-xs flex items-center gap-1"
                        >
                          <Mail className="w-3 h-3" />
                          이메일
                        </button>
                      </div>
                    </div>
                  </div>
                )}
                
                {/* 영어 버전 */}
                {generatedContent.voucher.en && (
                  <div className="border rounded p-2 bg-gray-50">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-700">🇺🇸 English</span>
                      <div className="flex gap-1">
                        <button
                          onClick={() => {
                            setPreviewDoc('voucher')
                            setPreviewLanguage('en')
                          }}
                          className="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-xs flex items-center gap-1"
                        >
                          <Eye className="w-3 h-3" />
                          Preview
                        </button>
                        <button
                          onClick={() => downloadDocument('voucher', 'en')}
                          className="px-2 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200 text-xs flex items-center gap-1"
                        >
                          <Download className="w-3 h-3" />
                          Download
                        </button>
                        <button
                          onClick={() => sendEmail('voucher', 'en')}
                          className="px-2 py-1 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-xs flex items-center gap-1"
                        >
                          <Mail className="w-3 h-3" />
                          Email
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* 픽업 안내 */}
        <div className="border rounded-lg p-4 bg-white">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-5 h-5 text-green-600" />
            <h4 className="font-medium text-gray-900">픽업 안내</h4>
            {(generatedContent.pickup.ko || generatedContent.pickup.en) && (
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            )}
          </div>
          
          <div className="space-y-2">
            <div className="flex gap-2">
              <button
                onClick={() => generateDocument('pickup', false, 'ko')}
                disabled={generating}
                className="flex-1 px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:opacity-50 text-sm"
              >
                {generating ? '생성 중...' : '한국어 생성'}
              </button>
              <button
                onClick={() => generateDocument('pickup', false, 'en')}
                disabled={generating}
                className="flex-1 px-3 py-2 bg-green-500 text-white rounded hover:bg-green-600 disabled:opacity-50 text-sm"
              >
                {generating ? '생성 중...' : 'English 생성'}
              </button>
            </div>
            
            {(generatedContent.pickup.ko || generatedContent.pickup.en) && (
              <div className="space-y-2">
                {/* 한국어 버전 */}
                {generatedContent.pickup.ko && (
                  <div className="border rounded p-2 bg-gray-50">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-700">🇰🇷 한국어</span>
                      <div className="flex gap-1">
                        <button
                          onClick={() => {
                            setPreviewDoc('pickup')
                            setPreviewLanguage('ko')
                          }}
                          className="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-xs flex items-center gap-1"
                        >
                          <Eye className="w-3 h-3" />
                          미리보기
                        </button>
                        <button
                          onClick={() => downloadDocument('pickup', 'ko')}
                          className="px-2 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200 text-xs flex items-center gap-1"
                        >
                          <Download className="w-3 h-3" />
                          다운로드
                        </button>
                        <button
                          onClick={() => sendEmail('pickup', 'ko')}
                          className="px-2 py-1 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-xs flex items-center gap-1"
                        >
                          <Mail className="w-3 h-3" />
                          이메일
                        </button>
                      </div>
                    </div>
                  </div>
                )}
                
                {/* 영어 버전 */}
                {generatedContent.pickup.en && (
                  <div className="border rounded p-2 bg-gray-50">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium text-gray-700">🇺🇸 English</span>
                      <div className="flex gap-1">
                        <button
                          onClick={() => {
                            setPreviewDoc('pickup')
                            setPreviewLanguage('en')
                          }}
                          className="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-xs flex items-center gap-1"
                        >
                          <Eye className="w-3 h-3" />
                          Preview
                        </button>
                        <button
                          onClick={() => downloadDocument('pickup', 'en')}
                          className="px-2 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200 text-xs flex items-center gap-1"
                        >
                          <Download className="w-3 h-3" />
                          Download
                        </button>
                        <button
                          onClick={() => sendEmail('pickup', 'en')}
                          className="px-2 py-1 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-xs flex items-center gap-1"
                        >
                          <Mail className="w-3 h-3" />
                          Email
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* 미리보기 모달 */}
      {previewDoc && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg w-full max-w-4xl max-h-[90vh] overflow-hidden">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <h2 className="text-xl font-bold text-gray-900">
                    {previewDoc === 'voucher' ? '투어 바우처 미리보기' : '픽업 안내 미리보기'}
                  </h2>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setPreviewLanguage('ko')}
                      className={`px-3 py-1 rounded text-sm ${
                        previewLanguage === 'ko' 
                          ? 'bg-blue-600 text-white' 
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      🇰🇷 한국어
                    </button>
                    <button
                      onClick={() => setPreviewLanguage('en')}
                      className={`px-3 py-1 rounded text-sm ${
                        previewLanguage === 'en' 
                          ? 'bg-blue-600 text-white' 
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      🇺🇸 English
                    </button>
                  </div>
                </div>
                <button
                  onClick={() => setPreviewDoc(null)}
                  className="text-gray-400 hover:text-gray-600 text-2xl"
                >
                  ×
                </button>
              </div>
              
              <div className="border rounded-lg p-6 bg-white overflow-y-auto max-h-[70vh]">
                <div dangerouslySetInnerHTML={{ __html: generatedContent[previewDoc][previewLanguage] }} />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
