'use client'

import { useState, useEffect } from 'react'
import { FileText, Mail, Download, Eye } from 'lucide-react'
import { generateTemplateContext } from '@/lib/templateContext'
import { renderTemplateString } from '@/lib/template'

interface SimpleDocumentGeneratorProps {
  reservationId: string
  customerName: string
  productName: string
  tourDate: string
  pickupTime: string
  pickupLocation: string
}

export default function SimpleDocumentGenerator({
  reservationId,
  customerName,
  productName,
  tourDate,
  pickupTime,
  pickupLocation
}: SimpleDocumentGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [previewDoc, setPreviewDoc] = useState<null | 'voucher' | 'pickup'>(null)
  const [generatedContent, setGeneratedContent] = useState<{
    voucher: string
    pickup: string
  }>({ voucher: '', pickup: '' })
  const [autoGenerated, setAutoGenerated] = useState(false)

  // 컴포넌트 마운트 시 자동 생성
  useEffect(() => {
    if (reservationId && !autoGenerated) {
      autoGenerateDocuments()
    }
  }, [reservationId, autoGenerated])

  // 자동 문서 생성
  const autoGenerateDocuments = async () => {
    if (autoGenerated) return
    
    setGenerating(true)
    setAutoGenerated(true)
    
    try {
      // 투어 바우처와 픽업 안내를 동시에 생성
      await Promise.all([
        generateDocument('voucher', true),
        generateDocument('pickup', true)
      ])
      
      console.log('자동 문서 생성 완료')
    } catch (error) {
      console.error('자동 문서 생성 오류:', error)
    } finally {
      setGenerating(false)
    }
  }

  // 간단한 템플릿들
  const templates = {
    voucher: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #2563eb; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #2563eb; margin: 0;">🎫 투어 바우처</h1>
          <p style="color: #666; margin: 5px 0;">Tour Voucher</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">예약번호: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">예약 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">고객명:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">이메일:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.email}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">예약 상태:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.status}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">상품 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">상품명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_ko}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">영문명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_en}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">카테고리:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.category}} - {{product.sub_category}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 날짜:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 시간:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.tour_time}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">픽업 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">픽업 시간:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 장소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.display}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 위치:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">주소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">투어 인원</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">성인:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.adults}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">아동:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.child}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">유아:</td>
              <td style="padding: 8px 0; color: #111827;">{{reservation.infant}}명</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">총 인원:</td>
              <td style="padding: 8px 0; color: #111827; font-weight: bold;">{{reservation.total_people}}명</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">📋 중요 안내사항</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li>투어 당일 픽업 시간 10분 전까지 픽업 장소에 도착해 주세요</li>
            <li>신분증을 지참해 주세요</li>
            <li>날씨에 따라 일정이 변경될 수 있습니다</li>
            <li>문의사항이 있으시면 연락주세요</li>
            <li>이 바우처를 투어 당일 가이드에게 제시해 주세요</li>
          </ul>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>감사합니다! 즐거운 투어 되세요! 🎉</p>
          <p style="margin: 5px 0; font-size: 12px;">문의: {{channel.name}}</p>
        </div>
      </div>
    `,
    
    pickup: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #059669; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #059669; margin: 0;">🚌 픽업 안내</h1>
          <p style="color: #666; margin: 5px 0;">Pickup Information</p>
          <p style="color: #999; font-size: 12px; margin: 5px 0;">예약번호: {{reservation.id}}</p>
        </div>
        
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">고객 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">고객명:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{customer.phone}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">투어 날짜:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 16px; font-weight: bold;">{{reservation.tour_date}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">상품명:</td>
              <td style="padding: 8px 0; color: #111827;">{{product.name_ko}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #dbeafe; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">📍 픽업 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">픽업 시간:</td>
              <td style="padding: 8px 0; color: #111827; font-size: 20px; font-weight: bold; color: #dc2626;">{{reservation.pickup_time}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 호텔:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.hotel_name}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">픽업 위치:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.pick_up_location}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">주소:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.address}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">안내:</td>
              <td style="padding: 8px 0; color: #111827;">{{pickup.description_ko}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #92400e; margin-top: 0;">🚗 차량 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">차량 유형:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.type || '투어 버스'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">차량 번호:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.plate_number || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">운전사:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin-top: 0;">👨‍🏫 가이드 정보</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">가이드명:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.name || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">연락처:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">언어:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.language || '한국어'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">경험:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.experience || '풍부한 경험'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #92400e; margin-top: 0;">⚠️ 중요 안내사항</h3>
          <ul style="color: #92400e; margin: 0; padding-left: 20px;">
            <li><strong>픽업 시간 10분 전까지 도착해 주세요</strong></li>
            <li>버스는 정시에 출발합니다 (늦으실 경우 다음 픽업 장소로 이동)</li>
            <li>신분증을 지참해 주세요</li>
            <li>날씨에 따라 일정이 변경될 수 있습니다</li>
            <li>긴급상황 시 가이드 또는 운전사에게 연락주세요</li>
            <li>투어 바우처를 가이드에게 제시해 주세요</li>
          </ul>
        </div>

        <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #047857; margin-top: 0;">📞 연락처</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 30%;">가이드:</td>
              <td style="padding: 8px 0; color: #111827;">{{guide.phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">운전사:</td>
              <td style="padding: 8px 0; color: #111827;">{{vehicle.driver_phone || 'TBD'}}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">고객센터:</td>
              <td style="padding: 8px 0; color: #111827;">{{channel.contact_phone || 'TBD'}}</td>
            </tr>
          </table>
        </div>
        
        <div style="text-align: center; color: #666; font-size: 14px;">
          <p>안전하고 즐거운 투어 되세요! 🚌✨</p>
          <p style="margin: 5px 0; font-size: 12px;">문의: {{channel.name}}</p>
        </div>
      </div>
    `
  }

  const generateDocument = async (type: 'voucher' | 'pickup', isAuto = false) => {
    if (!isAuto) {
      setGenerating(true)
    }
    
    try {
      console.log(`${type} 문서 생성 시작...`)
      
      // 템플릿 컨텍스트 생성 (에러가 발생해도 기본 데이터 사용)
      let context = null
      try {
        context = await generateTemplateContext(reservationId, 'ko')
        console.log('템플릿 컨텍스트 생성 완료:', context ? Object.keys(context) : 'null')
      } catch (error) {
        console.warn('템플릿 컨텍스트 생성 실패:', error)
        console.log('기본 컨텍스트 데이터 사용')
        // 기본 컨텍스트 데이터 제공
        context = {
          reservation: {
            id: reservationId,
            tour_date: tourDate,
            pickup_time: pickupTime,
            tour_time: '09:00',
            adults: 2,
            child: 0,
            infant: 0,
            total_people: 2,
            total_price: 100000,
            status: 'confirmed'
          },
          customer: {
            name: customerName || '고객',
            email: 'customer@example.com',
            phone: '010-0000-0000',
            language: 'ko'
          },
          product: {
            name_ko: productName || '투어 상품',
            name_en: 'Tour Product',
            category: '투어',
            sub_category: '일반'
          },
          channel: {
            name: '일반 채널',
            type: 'direct',
            contact_phone: '02-0000-0000'
          },
          pickup: {
            display: pickupLocation || '기본 픽업 호텔',
            hotel_name: pickupLocation || '기본 픽업 호텔',
            pick_up_location: '호텔 로비',
            address: '서울시 강남구',
            description_ko: '호텔 로비에서 픽업',
            description_en: 'Pickup at hotel lobby'
          },
          vehicle: {
            type: '투어 버스',
            plate_number: 'TBD',
            driver_name: 'TBD',
            driver_phone: 'TBD'
          },
          guide: {
            name: 'TBD',
            phone: 'TBD',
            language: '한국어',
            experience: '풍부한 경험'
          }
        }
      }
      
      if (!context) {
        console.error('템플릿 컨텍스트 생성 실패')
        return
      }
      
      // 템플릿 렌더링
      const renderedContent = renderTemplateString(templates[type], context)
      
      setGeneratedContent(prev => ({
        ...prev,
        [type]: renderedContent
      }))
      
      console.log(`${type} 문서 생성 완료`)
    } catch (error) {
      console.error(`${type} 문서 생성 오류:`, error)
      // 오류 발생 시에도 기본 문서 생성
      const fallbackContext = {
        reservation: {
          id: reservationId,
          tour_date: tourDate,
          pickup_time: pickupTime,
          tour_time: '09:00',
          adults: 2,
          child: 0,
          infant: 0,
          total_people: 2,
          total_price: 100000,
          status: 'confirmed'
        },
        customer: {
          name: customerName || '고객',
          email: 'customer@example.com',
          phone: '010-0000-0000',
          language: 'ko'
        },
        product: {
          name_ko: productName || '투어 상품',
          name_en: 'Tour Product',
          category: '투어',
          sub_category: '일반'
        },
        channel: {
          name: '일반 채널',
          type: 'direct',
          contact_phone: '02-0000-0000'
        },
        pickup: {
          display: pickupLocation || '기본 픽업 호텔',
          hotel_name: pickupLocation || '기본 픽업 호텔',
          pick_up_location: '호텔 로비',
          address: '서울시 강남구',
          description_ko: '호텔 로비에서 픽업',
          description_en: 'Pickup at hotel lobby'
        },
        vehicle: {
          type: '투어 버스',
          plate_number: 'TBD',
          driver_name: 'TBD',
          driver_phone: 'TBD'
        },
        guide: {
          name: 'TBD',
          phone: 'TBD',
          language: '한국어',
          experience: '풍부한 경험'
        }
      }
      
      const renderedContent = renderTemplateString(templates[type], fallbackContext)
      setGeneratedContent(prev => ({
        ...prev,
        [type]: renderedContent
      }))
    } finally {
      if (!isAuto) {
        setGenerating(false)
      }
    }
  }

  const downloadDocument = (type: 'voucher' | 'pickup') => {
    const content = generatedContent[type]
    if (!content) return
    
    const blob = new Blob([content], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${type === 'voucher' ? '투어바우처' : '픽업안내'}_${customerName}_${tourDate}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const sendEmail = (type: 'voucher' | 'pickup') => {
    const content = generatedContent[type]
    if (!content) return
    
    const subject = type === 'voucher' ? '투어 바우처' : '픽업 안내'
    const body = encodeURIComponent(content)
    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${body}`
    window.open(mailtoLink)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900">📄 간편 문서 생성</h3>
        {autoGenerated && (
          <div className="flex items-center gap-2 text-sm text-green-600">
            <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            자동 생성 완료
          </div>
        )}
      </div>
      
      {generating && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
            <span className="text-blue-700">문서를 자동 생성하고 있습니다...</span>
          </div>
        </div>
      )}
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* 투어 바우처 */}
        <div className="border rounded-lg p-4 bg-white">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-5 h-5 text-blue-600" />
            <h4 className="font-medium text-gray-900">투어 바우처</h4>
            {generatedContent.voucher && (
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            )}
          </div>
          
          <div className="space-y-2">
            <button
              onClick={() => generateDocument('voucher')}
              disabled={generating}
              className="w-full px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 text-sm"
            >
              {generating ? '생성 중...' : generatedContent.voucher ? '다시 생성' : '바우처 생성'}
            </button>
            
            {generatedContent.voucher && (
              <div className="flex gap-2">
                <button
                  onClick={() => setPreviewDoc(previewDoc === 'voucher' ? null : 'voucher')}
                  className="flex-1 px-3 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-sm flex items-center justify-center gap-1"
                >
                  <Eye className="w-4 h-4" />
                  미리보기
                </button>
                <button
                  onClick={() => downloadDocument('voucher')}
                  className="flex-1 px-3 py-2 bg-green-100 text-green-700 rounded hover:bg-green-200 text-sm flex items-center justify-center gap-1"
                >
                  <Download className="w-4 h-4" />
                  다운로드
                </button>
                <button
                  onClick={() => sendEmail('voucher')}
                  className="flex-1 px-3 py-2 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-sm flex items-center justify-center gap-1"
                >
                  <Mail className="w-4 h-4" />
                  이메일
                </button>
              </div>
            )}
          </div>
        </div>

        {/* 픽업 안내 */}
        <div className="border rounded-lg p-4 bg-white">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-5 h-5 text-green-600" />
            <h4 className="font-medium text-gray-900">픽업 안내</h4>
            {generatedContent.pickup && (
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            )}
          </div>
          
          <div className="space-y-2">
            <button
              onClick={() => generateDocument('pickup')}
              disabled={generating}
              className="w-full px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:opacity-50 text-sm"
            >
              {generating ? '생성 중...' : generatedContent.pickup ? '다시 생성' : '픽업 안내 생성'}
            </button>
            
            {generatedContent.pickup && (
              <div className="flex gap-2">
                <button
                  onClick={() => setPreviewDoc(previewDoc === 'pickup' ? null : 'pickup')}
                  className="flex-1 px-3 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-sm flex items-center justify-center gap-1"
                >
                  <Eye className="w-4 h-4" />
                  미리보기
                </button>
                <button
                  onClick={() => downloadDocument('pickup')}
                  className="flex-1 px-3 py-2 bg-green-100 text-green-700 rounded hover:bg-green-200 text-sm flex items-center justify-center gap-1"
                >
                  <Download className="w-4 h-4" />
                  다운로드
                </button>
                <button
                  onClick={() => sendEmail('pickup')}
                  className="flex-1 px-3 py-2 bg-purple-100 text-purple-700 rounded hover:bg-purple-200 text-sm flex items-center justify-center gap-1"
                >
                  <Mail className="w-4 h-4" />
                  이메일
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* 미리보기 모달 */}
      {previewDoc && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg w-full max-w-4xl max-h-[90vh] overflow-hidden">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-gray-900">
                  {previewDoc === 'voucher' ? '투어 바우처 미리보기' : '픽업 안내 미리보기'}
                </h2>
                <button
                  onClick={() => setPreviewDoc(null)}
                  className="text-gray-400 hover:text-gray-600 text-2xl"
                >
                  ×
                </button>
              </div>
              
              <div className="border rounded-lg p-6 bg-white overflow-y-auto max-h-[70vh]">
                <div dangerouslySetInnerHTML={{ __html: generatedContent[previewDoc] }} />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
