import { ColumnInfo, ColumnMapping } from '@/types/data-sync'

export const getAutoCompleteSuggestions = (dbColumn: string, sheetColumns: string[]): string[] => {
  const suggestions: string[] = []
  const dbLower = dbColumn.toLowerCase()
  
  sheetColumns.forEach(sheetCol => {
    const sheetLower = sheetCol.toLowerCase()
    
    // 정확한 매칭 (대소문자 무시)
    if (dbLower === sheetLower) {
      suggestions.unshift(sheetCol) // 정확한 매칭을 맨 앞에
      return
    }
    
    // 부분 매칭 (포함 관계)
    if (dbLower.includes(sheetLower) || sheetLower.includes(dbLower)) {
      suggestions.push(sheetCol)
      return
    }
    
    // 언더스코어 제거 후 매칭 (예: customer_name -> customername)
    const dbWithoutUnderscore = dbLower.replace(/_/g, '')
    const sheetWithoutUnderscore = sheetLower.replace(/_/g, '')
    if (dbWithoutUnderscore === sheetWithoutUnderscore) {
      suggestions.push(sheetCol)
      return
    }
    
    // 한글 매핑 (일반적인 패턴) - 역방향 매핑
    const koreanMappings: { [key: string]: string[] } = {
      'id': ['예약번호', 'ID', '아이디'],
      'name': ['고객명', '이름', 'Name'],
      'nick_name': ['닉네임', 'Nickname', '별명', '별칭'],
      'customer_name': ['고객명', '이름', 'Name'],
      'email': ['이메일', 'Email', '메일'],
      'customer_email': ['이메일', 'Email', '메일'],
      'phone': ['전화번호', 'Phone', '연락처'],
      'customer_phone': ['전화번호', 'Phone', '연락처'],
      'adults': ['성인수', '성인', 'Adults'],
      'child': ['아동수', '아동', 'Child'],
      'infant': ['유아수', '유아', 'Infant'],
      'total_people': ['총인원', '인원', 'Total'],
      'tour_date': ['투어날짜', '날짜', 'Date'],
      'tour_time': ['투어시간', '시간', 'Time'],
      'product_id': ['상품ID', '상품', 'Product'],
      'tour_id': ['투어ID', '투어', 'Tour'],
      'pickup_hotel': ['픽업호텔', '호텔', 'Hotel'],
      'pickup_time': ['픽업시간', '픽업', 'Pickup'],
      'channel_id': ['채널', 'Channel'],
      'tour_status': ['상태', 'Status'],
      'notes': ['비고', '메모', 'Notes'],
      'tour_note': ['비고', '메모', 'Notes'],
      'event_note': ['비고', '메모', 'Notes'],
      'is_private_tour': ['개인투어', 'Private'],
      'tour_guide_id': ['가이드', 'Guide'],
      'guide_id': ['가이드', 'Guide'],
      'assistant_id': ['어시스턴트', 'Assistant'],
      'vehicle_id': ['차량', 'Vehicle'],
      'tour_car_id': ['차량', 'Vehicle'],
      'price': ['가격', 'Price'],
      'guide_fee': ['가이드비', 'Guide Fee'],
      'assistant_fee': ['어시스턴트비', 'Assistant Fee'],
      'created_at': ['생성일', 'Created'],
      'updated_at': ['수정일', 'Updated'],
      // Vehicles 테이블 매핑
      'vehicle_number': ['차량번호', 'Vehicle Number', '차량 번호'],
      'vin': ['VIN', '차대번호', '차대 번호'],
      'vehicle_type': ['차량종류', 'Vehicle Type', '차량 종류', '타입'],
      'capacity': ['정원', 'Capacity', '수용인원', '수용 인원'],
      'year': ['연식', 'Year', '연도'],
      'mileage_at_purchase': ['구매시주행거리', 'Purchase Mileage', '구매시 주행거리'],
      'purchase_amount': ['구매금액', 'Purchase Amount', '구매 금액', '가격'],
      'purchase_date': ['구매일', 'Purchase Date', '구매 날짜'],
      'memo': ['메모', 'Memo', '비고', 'Notes'],
      'engine_oil_change_cycle': ['엔진오일교환주기', 'Oil Change Cycle', '엔진오일 교환주기'],
      'current_mileage': ['현재주행거리', 'Current Mileage', '현재 주행거리'],
      'recent_engine_oil_change_mileage': ['최근엔진오일교환주행거리', 'Recent Oil Change Mileage', '최근 엔진오일 교환 주행거리'],
      'status': ['차량상태', 'Vehicle Status', '차량 상태', '상태', 'Status'],
      'front_tire_size': ['앞타이어사이즈', 'Front Tire Size', '앞 타이어 사이즈'],
      'rear_tire_size': ['뒤타이어사이즈', 'Rear Tire Size', '뒤 타이어 사이즈'],
      'windshield_wiper_size': ['와이퍼사이즈', 'Wiper Size', '와이퍼 사이즈'],
      'headlight_model': ['헤드라이트모델', 'Headlight Model', '헤드라이트 모델'],
      'headlight_model_name': ['헤드라이트모델명', 'Headlight Model Name', '헤드라이트 모델명'],
      'is_installment': ['할부여부', 'Installment', '할부 여부'],
      'installment_amount': ['할부금액', 'Installment Amount', '할부 금액'],
      'interest_rate': ['이자율', 'Interest Rate', '이자율'],
      'monthly_payment': ['월납입금', 'Monthly Payment', '월 납입금'],
      'additional_payment': ['추가납입금', 'Additional Payment', '추가 납입금'],
      'payment_due_date': ['납입일', 'Payment Due Date', '납입 날짜'],
      'installment_start_date': ['할부시작일', 'Installment Start Date', '할부 시작일'],
      // Off Schedules 테이블 매핑
      'team_email': ['팀이메일', 'Team Email', '이메일', 'Email'],
      'off_date': ['휴가날짜', 'Off Date', '휴가 날짜', '날짜', 'Date'],
      'reason': ['사유', 'Reason', '휴가사유', '휴가 사유'],
      'status': ['상태', 'Status'],
      'approved_by': ['승인자', 'Approved By', '승인한 사람'],
      'approved_at': ['승인일시', 'Approved At', '승인 날짜', '승인 시간'],
      // Payment Records 테이블 매핑
      'reservation_id': ['예약번호', 'Reservation ID', '예약 ID', '예약아이디'],
      'payment_status': ['결제상태', 'Payment Status', '결제 상태', '상태'],
      'amount': ['금액', 'Amount', '결제금액', '결제 금액'],
      'payment_method': ['결제방법', 'Payment Method', '결제 방법', '방법'],
      'note': ['메모', 'Note', '비고', 'Notes'],
      'image_file_url': ['이미지파일', 'Image File', '이미지 파일', '파일'],
      'submit_on': ['제출일시', 'Submit On', '제출 날짜', '제출 시간'],
      'submit_by': ['제출자', 'Submit By', '제출한 사람'],
      'confirmed_on': ['확인일시', 'Confirmed On', '확인 날짜', '확인 시간'],
      'confirmed_by': ['확인자', 'Confirmed By', '확인한 사람'],
      'amount_krw': ['원화금액', 'Amount KRW', '원화 금액', 'KRW'],
      // Reservation Expenses 테이블 매핑
      'submitted_by': ['제출자', 'Submitted By', '제출한 사람'],
      'paid_to': ['지급대상', 'Paid To', '지급 대상', '받는 사람'],
      'paid_for': ['지급목적', 'Paid For', '지급 목적', '용도'],
      'image_url': ['이미지URL', 'Image URL', '이미지 URL', '사진'],
      'file_path': ['파일경로', 'File Path', '파일 경로', '첨부파일'],
      'event_id': ['이벤트ID', 'Event ID', '이벤트 ID', '이벤트아이디'],
      'audited_by': ['감사자', 'Audited By', '감사한 사람'],
      'checked_by': ['확인자', 'Checked By', '확인한 사람'],
      'checked_on': ['확인일시', 'Checked On', '확인 날짜', '확인 시간'],
      // Company Expenses 테이블 매핑
      'description': ['설명', 'Description', '내용', '비고'],
      'submit_by': ['제출자', 'Submit By', '제출한 사람'],
      'photo_url': ['사진URL', 'Photo URL', '사진 URL', '사진'],
      'category': ['카테고리', 'Category', '분류'],
      'subcategory': ['하위카테고리', 'Subcategory', '하위 분류'],
      'approved_by': ['승인자', 'Approved By', '승인한 사람'],
      'approved_on': ['승인일시', 'Approved On', '승인 날짜', '승인 시간'],
      'paid_by': ['지급자', 'Paid By', '지급한 사람'],
      'paid_on': ['지급일시', 'Paid On', '지급 날짜', '지급 시간'],
      'accounting_period': ['회계기간', 'Accounting Period', '회계 기간'],
      'expense_type': ['지출유형', 'Expense Type', '지출 유형'],
      'tax_deductible': ['세금공제', 'Tax Deductible', '세금 공제'],
      'vehicle_id': ['차량ID', 'Vehicle ID', '차량 ID', '차량아이디'],
      'maintenance_type': ['정비유형', 'Maintenance Type', '정비 유형'],
      'attachments': ['첨부파일', 'Attachments', '첨부 파일'],
      'created_by': ['생성자', 'Created By', '생성한 사람'],
      'updated_by': ['수정자', 'Updated By', '수정한 사람']
    }
    
    if (koreanMappings[dbColumn]) {
      koreanMappings[dbColumn].forEach(mapping => {
        if (sheetLower.includes(mapping.toLowerCase())) {
          suggestions.push(sheetCol)
        }
      })
    }
  })
  
  // 중복 제거 및 정렬
  return [...new Set(suggestions)].slice(0, 5) // 최대 5개 제안
}

export const getAutoMapping = (dbColumns: ColumnInfo[], sheetColumns: string[]): ColumnMapping => {
  const mapping: ColumnMapping = {}
  
  dbColumns.forEach(dbColumn => {
    const suggestions = getAutoCompleteSuggestions(dbColumn.name, sheetColumns)
    if (suggestions.length > 0) {
      // 가장 높은 우선순위의 제안을 선택
      mapping[suggestions[0]] = dbColumn.name
    }
  })
  
  return mapping
}

export const getFallbackColumns = (tableName: string): ColumnInfo[] => {
  const fallbackColumns: { [key: string]: ColumnInfo[] } = {
    pickup_hotels: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'hotel', type: 'text', nullable: false, default: null },
      { name: 'pick_up_location', type: 'text', nullable: false, default: null },
      { name: 'address', type: 'text', nullable: true, default: null },
      { name: 'pin', type: 'text', nullable: true, default: null },
      { name: 'link', type: 'text', nullable: true, default: null },
      { name: 'media', type: 'text[]', nullable: true, default: null },
      { name: 'description_ko', type: 'text', nullable: true, default: null },
      { name: 'description_en', type: 'text', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' },
    ],
    reservations: [
      { name: 'id', type: 'uuid', nullable: false, default: null },
      { name: 'customer_id', type: 'text', nullable: true, default: null },
      { name: 'product_id', type: 'text', nullable: true, default: null },
      { name: 'tour_id', type: 'text', nullable: true, default: null },
      { name: 'customer_name', type: 'text', nullable: true, default: null },
      { name: 'customer_email', type: 'text', nullable: true, default: null },
      { name: 'customer_phone', type: 'text', nullable: true, default: null },
      { name: 'adults', type: 'integer', nullable: true, default: null },
      { name: 'child', type: 'integer', nullable: true, default: null },
      { name: 'infant', type: 'integer', nullable: true, default: null },
      { name: 'total_people', type: 'integer', nullable: true, default: null },
      { name: 'tour_date', type: 'date', nullable: true, default: null },
      { name: 'tour_time', type: 'text', nullable: true, default: null },
      { name: 'pickup_hotel', type: 'text', nullable: true, default: null },
      { name: 'pickup_time', type: 'text', nullable: true, default: null },
      { name: 'channel', type: 'text', nullable: true, default: null },
      { name: 'channel_rn', type: 'text', nullable: true, default: null },
      { name: 'added_by', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'pending' },
      { name: 'event_note', type: 'text', nullable: true, default: null },
      { name: 'is_private_tour', type: 'boolean', nullable: true, default: 'false' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' },
    ],
    tours: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'product_id', type: 'text', nullable: true, default: null },
      { name: 'tour_date', type: 'date', nullable: true, default: null },
      { name: 'tour_status', type: 'text', nullable: true, default: 'Recruiting' },
      { name: 'tour_guide_id', type: 'uuid', nullable: true, default: null },
      { name: 'assistant_id', type: 'uuid', nullable: true, default: null },
      { name: 'tour_car_id', type: 'uuid', nullable: true, default: null },
      { name: 'is_private_tour', type: 'boolean', nullable: true, default: 'false' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    customers: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'name', type: 'text', nullable: true, default: null },
      { name: 'email', type: 'text', nullable: true, default: null },
      { name: 'phone', type: 'text', nullable: true, default: null },
      { name: 'language', type: 'text', nullable: true, default: 'ko' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    reservation_options: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'reservation_id', type: 'text', nullable: false, default: null },
      { name: 'option_id', type: 'text', nullable: false, default: null },
      { name: 'ea', type: 'integer', nullable: false, default: '1' },
      { name: 'price', type: 'decimal', nullable: false, default: '0' },
      { name: 'total_price', type: 'decimal', nullable: false, default: '0' },
      { name: 'status', type: 'text', nullable: true, default: 'active' },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    products: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'name', type: 'text', nullable: true, default: null },
      { name: 'description', type: 'text', nullable: true, default: null },
      { name: 'price', type: 'numeric', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    ticket_bookings: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'category', type: 'text', nullable: true, default: null },
      { name: 'submit_on', type: 'date', nullable: true, default: null },
      { name: 'submitted_by', type: 'text', nullable: true, default: null },
      { name: 'check_in_date', type: 'date', nullable: true, default: null },
      { name: 'time', type: 'time', nullable: true, default: null },
      { name: 'company', type: 'text', nullable: true, default: null },
      { name: 'ea', type: 'integer', nullable: true, default: null },
      { name: 'expense', type: 'numeric', nullable: true, default: null },
      { name: 'income', type: 'numeric', nullable: true, default: null },
      { name: 'payment_method', type: 'text', nullable: true, default: null },
      { name: 'rn_number', type: 'text', nullable: true, default: null },
      { name: 'tour_id', type: 'text', nullable: true, default: null },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: null },
      { name: 'season', type: 'text', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'reservation_id', type: 'text', nullable: true, default: null }
    ],
    tour_hotel_bookings: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()::text' },
      { name: 'tour_id', type: 'text', nullable: true, default: null },
      { name: 'event_date', type: 'date', nullable: false, default: null },
      { name: 'submit_on', type: 'timestamp', nullable: true, default: 'now()' },
      { name: 'check_in_date', type: 'date', nullable: false, default: null },
      { name: 'check_out_date', type: 'date', nullable: false, default: null },
      { name: 'reservation_name', type: 'text', nullable: false, default: null },
      { name: 'submitted_by', type: 'text', nullable: true, default: null },
      { name: 'cc', type: 'text', nullable: true, default: null },
      { name: 'rooms', type: 'integer', nullable: false, default: '1' },
      { name: 'city', type: 'text', nullable: false, default: null },
      { name: 'hotel', type: 'text', nullable: false, default: null },
      { name: 'room_type', type: 'text', nullable: true, default: null },
      { name: 'unit_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'total_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'payment_method', type: 'text', nullable: true, default: null },
      { name: 'website', type: 'text', nullable: true, default: null },
      { name: 'rn_number', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'pending' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    vehicles: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'vehicle_number', type: 'text', nullable: true, default: null },
      { name: 'vin', type: 'text', nullable: true, default: null },
      { name: 'vehicle_type', type: 'text', nullable: true, default: null },
      { name: 'capacity', type: 'integer', nullable: true, default: null },
      { name: 'year', type: 'integer', nullable: true, default: null },
      { name: 'mileage_at_purchase', type: 'integer', nullable: true, default: null },
      { name: 'purchase_amount', type: 'numeric', nullable: true, default: null },
      { name: 'purchase_date', type: 'date', nullable: true, default: null },
      { name: 'memo', type: 'text', nullable: true, default: null },
      { name: 'engine_oil_change_cycle', type: 'integer', nullable: true, default: null },
      { name: 'current_mileage', type: 'integer', nullable: true, default: null },
      { name: 'recent_engine_oil_change_mileage', type: 'integer', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: false, default: "'운행 가능'" },
      { name: 'front_tire_size', type: 'text', nullable: true, default: null },
      { name: 'rear_tire_size', type: 'text', nullable: true, default: null },
      { name: 'windshield_wiper_size', type: 'text', nullable: true, default: null },
      { name: 'headlight_model', type: 'text', nullable: true, default: null },
      { name: 'headlight_model_name', type: 'text', nullable: true, default: null },
      { name: 'is_installment', type: 'boolean', nullable: true, default: 'false' },
      { name: 'installment_amount', type: 'numeric', nullable: true, default: null },
      { name: 'interest_rate', type: 'numeric', nullable: true, default: null },
      { name: 'monthly_payment', type: 'numeric', nullable: true, default: null },
      { name: 'additional_payment', type: 'numeric', nullable: true, default: null },
      { name: 'payment_due_date', type: 'date', nullable: true, default: null },
      { name: 'installment_start_date', type: 'date', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    tour_expenses: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'tour_id', type: 'text', nullable: false, default: null },
      { name: 'submit_on', type: 'timestamp', nullable: true, default: 'now()' },
      { name: 'paid_to', type: 'text', nullable: true, default: null },
      { name: 'paid_for', type: 'text', nullable: false, default: null },
      { name: 'amount', type: 'numeric', nullable: false, default: null },
      { name: 'payment_method', type: 'text', nullable: true, default: null },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'tour_date', type: 'date', nullable: false, default: null },
      { name: 'product_id', type: 'text', nullable: true, default: null },
      { name: 'submitted_by', type: 'text', nullable: false, default: null },
      { name: 'image_url', type: 'text', nullable: true, default: null },
      { name: 'file_path', type: 'text', nullable: true, default: null },
      { name: 'audited_by', type: 'text', nullable: true, default: null },
      { name: 'checked_by', type: 'text', nullable: true, default: null },
      { name: 'checked_on', type: 'timestamp', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'pending' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    payment_methods: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'method', type: 'text', nullable: false, default: null },
      { name: 'method_type', type: 'text', nullable: false, default: 'card' },
      { name: 'user_email', type: 'text', nullable: false, default: null },
      { name: 'limit_amount', type: 'numeric', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'active' },
      { name: 'card_number_last4', type: 'text', nullable: true, default: null },
      { name: 'card_type', type: 'text', nullable: true, default: null },
      { name: 'card_holder_name', type: 'text', nullable: true, default: null },
      { name: 'expiry_date', type: 'date', nullable: true, default: null },
      { name: 'monthly_limit', type: 'numeric', nullable: true, default: null },
      { name: 'daily_limit', type: 'numeric', nullable: true, default: null },
      { name: 'current_month_usage', type: 'numeric', nullable: false, default: '0' },
      { name: 'current_day_usage', type: 'numeric', nullable: false, default: '0' },
      { name: 'assigned_date', type: 'date', nullable: false, default: 'current_date' },
      { name: 'last_used_date', type: 'timestamp', nullable: true, default: null },
      { name: 'notes', type: 'text', nullable: true, default: null },
      { name: 'created_by', type: 'text', nullable: true, default: null },
      { name: 'updated_by', type: 'text', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    reservation_expenses: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'submit_on', type: 'timestamp', nullable: true, default: 'now()' },
      { name: 'submitted_by', type: 'text', nullable: false, default: null },
      { name: 'paid_to', type: 'text', nullable: false, default: null },
      { name: 'paid_for', type: 'text', nullable: false, default: null },
      { name: 'amount', type: 'numeric', nullable: false, default: null },
      { name: 'payment_method', type: 'text', nullable: true, default: null },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'image_url', type: 'text', nullable: true, default: null },
      { name: 'file_path', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'pending' },
      { name: 'reservation_id', type: 'text', nullable: true, default: null },
      { name: 'event_id', type: 'text', nullable: true, default: null },
      { name: 'audited_by', type: 'text', nullable: true, default: null },
      { name: 'checked_by', type: 'text', nullable: true, default: null },
      { name: 'checked_on', type: 'timestamp', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    team: [
      { name: 'email', type: 'text', nullable: false, default: null },
      { name: 'name_ko', type: 'text', nullable: false, default: null },
      { name: 'name_en', type: 'text', nullable: true, default: null },
      { name: 'nick_name', type: 'text', nullable: true, default: null },
      { name: 'phone', type: 'text', nullable: false, default: null },
      { name: 'position', type: 'text', nullable: true, default: null },
      { name: 'languages', type: 'text[]', nullable: true, default: '{}' },
      { name: 'avatar_url', type: 'text', nullable: true, default: null },
      { name: 'is_active', type: 'boolean', nullable: true, default: 'true' },
      { name: 'hire_date', type: 'date', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'active' },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'emergency_contact', type: 'text', nullable: true, default: null },
      { name: 'date_of_birth', type: 'date', nullable: true, default: null },
      { name: 'ssn', type: 'text', nullable: true, default: null },
      { name: 'personal_car_model', type: 'text', nullable: true, default: null },
      { name: 'car_year', type: 'integer', nullable: true, default: null },
      { name: 'car_plate', type: 'text', nullable: true, default: null },
      { name: 'bank_name', type: 'text', nullable: true, default: null },
      { name: 'account_holder', type: 'text', nullable: true, default: null },
      { name: 'bank_number', type: 'text', nullable: true, default: null },
      { name: 'routing_number', type: 'text', nullable: true, default: null },
      { name: 'cpr', type: 'boolean', nullable: true, default: 'false' },
      { name: 'cpr_acquired', type: 'date', nullable: true, default: null },
      { name: 'cpr_expired', type: 'date', nullable: true, default: null },
      { name: 'medical_report', type: 'boolean', nullable: true, default: 'false' },
      { name: 'medical_acquired', type: 'date', nullable: true, default: null },
      { name: 'medical_expired', type: 'date', nullable: true, default: null },
      { name: 'address', type: 'text', nullable: true, default: null }
    ],
    reservation_pricing: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()::text' },
      { name: 'reservation_id', type: 'text', nullable: false, default: null },
      { name: 'adult_product_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'child_product_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'infant_product_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'product_price_total', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'required_options', type: 'jsonb', nullable: true, default: '{}' },
      { name: 'required_option_total', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'subtotal', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'coupon_code', type: 'text', nullable: true, default: null },
      { name: 'coupon_discount', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'additional_discount', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'additional_cost', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'card_fee', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'tax', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'prepayment_cost', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'prepayment_tip', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'selected_options', type: 'jsonb', nullable: true, default: '{}' },
      { name: 'option_total', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'is_private_tour', type: 'boolean', nullable: true, default: 'false' },
      { name: 'private_tour_additional_cost', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'total_price', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'deposit_amount', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'balance_amount', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'commission_percent', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'commission_amount', type: 'numeric', nullable: true, default: '0.00' },
      { name: 'created_at', type: 'timestamp', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: true, default: 'now()' }
    ],
    off_schedules: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      { name: 'team_email', type: 'character varying(255)', nullable: false, default: null },
      { name: 'off_date', type: 'date', nullable: false, default: null },
      { name: 'reason', type: 'text', nullable: false, default: null },
      { name: 'status', type: 'text', nullable: false, default: "'pending'" },
      { name: 'approved_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'approved_at', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ],
    payment_records: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()' },
      { name: 'reservation_id', type: 'text', nullable: false, default: null },
      { name: 'payment_status', type: 'character varying(50)', nullable: false, default: "'pending'" },
      { name: 'amount', type: 'numeric(10, 2)', nullable: false, default: null },
      { name: 'payment_method', type: 'character varying(50)', nullable: false, default: null },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'image_file_url', type: 'text', nullable: true, default: null },
      { name: 'submit_on', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'submit_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'confirmed_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'confirmed_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'amount_krw', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ],
    company_expenses: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'submit_on', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'paid_to', type: 'character varying(255)', nullable: false, default: null },
      { name: 'paid_for', type: 'text', nullable: false, default: null },
      { name: 'description', type: 'text', nullable: true, default: null },
      { name: 'amount', type: 'numeric(10, 2)', nullable: false, default: null },
      { name: 'payment_method', type: 'character varying(100)', nullable: true, default: null },
      { name: 'submit_by', type: 'character varying(255)', nullable: false, default: null },
      { name: 'photo_url', type: 'text', nullable: true, default: null },
      { name: 'category', type: 'character varying(100)', nullable: true, default: null },
      { name: 'subcategory', type: 'character varying(100)', nullable: true, default: null },
      { name: 'status', type: 'character varying(50)', nullable: true, default: "'pending'" },
      { name: 'approved_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'approved_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'paid_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'paid_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'accounting_period', type: 'character varying(20)', nullable: true, default: null },
      { name: 'expense_type', type: 'character varying(50)', nullable: true, default: null },
      { name: 'tax_deductible', type: 'boolean', nullable: true, default: 'true' },
      { name: 'vehicle_id', type: 'text', nullable: true, default: null },
      { name: 'maintenance_type', type: 'character varying(100)', nullable: true, default: null },
      { name: 'notes', type: 'text', nullable: true, default: null },
      { name: 'attachments', type: 'text[]', nullable: true, default: null },
      { name: 'created_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'updated_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ],
    vehicle_maintenance: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()' },
      { name: 'vehicle_id', type: 'text', nullable: false, default: null },
      { name: 'maintenance_date', type: 'date', nullable: false, default: null },
      { name: 'mileage', type: 'integer', nullable: true, default: null },
      { name: 'maintenance_type', type: 'character varying(100)', nullable: false, default: null },
      { name: 'category', type: 'character varying(100)', nullable: false, default: null },
      { name: 'subcategory', type: 'character varying(100)', nullable: true, default: null },
      { name: 'description', type: 'text', nullable: false, default: null },
      { name: 'total_cost', type: 'numeric(10, 2)', nullable: false, default: null },
      { name: 'labor_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'parts_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'other_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'service_provider', type: 'character varying(255)', nullable: true, default: null },
      { name: 'service_provider_contact', type: 'character varying(255)', nullable: true, default: null },
      { name: 'service_provider_address', type: 'text', nullable: true, default: null },
      { name: 'warranty_period', type: 'integer', nullable: true, default: null },
      { name: 'warranty_expires', type: 'date', nullable: true, default: null },
      { name: 'warranty_notes', type: 'text', nullable: true, default: null },
      { name: 'is_scheduled_maintenance', type: 'boolean', nullable: true, default: 'false' },
      { name: 'next_maintenance_date', type: 'date', nullable: true, default: null },
      { name: 'next_maintenance_mileage', type: 'integer', nullable: true, default: null },
      { name: 'maintenance_interval', type: 'integer', nullable: true, default: null },
      { name: 'mileage_interval', type: 'integer', nullable: true, default: null },
      { name: 'parts_replaced', type: 'text[]', nullable: true, default: null },
      { name: 'parts_cost_breakdown', type: 'jsonb', nullable: true, default: null },
      { name: 'quality_rating', type: 'integer', nullable: true, default: null },
      { name: 'satisfaction_rating', type: 'integer', nullable: true, default: null },
      { name: 'issues_found', type: 'text[]', nullable: true, default: null },
      { name: 'recommendations', type: 'text[]', nullable: true, default: null },
      { name: 'photos', type: 'text[]', nullable: true, default: null },
      { name: 'receipts', type: 'text[]', nullable: true, default: null },
      { name: 'documents', type: 'text[]', nullable: true, default: null },
      { name: 'notes', type: 'text', nullable: true, default: null },
      { name: 'technician_notes', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'character varying(50)', nullable: true, default: "'completed'" },
      { name: 'approved_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'approved_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'company_expense_id', type: 'text', nullable: true, default: null },
      { name: 'created_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'updated_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ],
    reservation_expenses: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()' },
      { name: 'submit_on', type: 'timestamp with time zone', nullable: false, default: 'now()' },
      { name: 'submitted_by', type: 'character varying(255)', nullable: false, default: null },
      { name: 'paid_to', type: 'character varying(255)', nullable: false, default: null },
      { name: 'paid_for', type: 'character varying(255)', nullable: false, default: null },
      { name: 'amount', type: 'numeric(10, 2)', nullable: false, default: null },
      { name: 'payment_method', type: 'character varying(100)', nullable: true, default: null },
      { name: 'note', type: 'text', nullable: true, default: null },
      { name: 'image_url', type: 'text', nullable: true, default: null },
      { name: 'file_path', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'character varying(50)', nullable: true, default: "'pending'" },
      { name: 'reservation_id', type: 'text', nullable: true, default: null },
      { name: 'event_id', type: 'text', nullable: true, default: null },
      { name: 'audited_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'checked_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'checked_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ],
    payment_methods: [
      { name: 'id', type: 'text', nullable: false, default: null },
      { name: 'method', type: 'text', nullable: false, default: null },
      { name: 'method_type', type: 'text', nullable: false, default: 'card' },
      { name: 'user_email', type: 'text', nullable: false, default: null },
      { name: 'limit_amount', type: 'numeric', nullable: true, default: null },
      { name: 'status', type: 'text', nullable: true, default: 'active' },
      { name: 'card_number_last4', type: 'text', nullable: true, default: null },
      { name: 'card_type', type: 'text', nullable: true, default: null },
      { name: 'card_holder_name', type: 'text', nullable: true, default: null },
      { name: 'expiry_date', type: 'date', nullable: true, default: null },
      { name: 'monthly_limit', type: 'numeric', nullable: true, default: null },
      { name: 'daily_limit', type: 'numeric', nullable: true, default: null },
      { name: 'current_month_usage', type: 'numeric', nullable: false, default: '0' },
      { name: 'current_day_usage', type: 'numeric', nullable: false, default: '0' },
      { name: 'assigned_date', type: 'date', nullable: false, default: 'current_date' },
      { name: 'last_used_date', type: 'timestamp', nullable: true, default: null },
      { name: 'notes', type: 'text', nullable: true, default: null },
      { name: 'created_by', type: 'text', nullable: true, default: null },
      { name: 'updated_by', type: 'text', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp', nullable: false, default: 'now()' },
      { name: 'updated_at', type: 'timestamp', nullable: false, default: 'now()' }
    ],
    vehicle_maintenance: [
      { name: 'id', type: 'text', nullable: false, default: 'gen_random_uuid()' },
      { name: 'vehicle_id', type: 'text', nullable: false, default: null },
      { name: 'maintenance_date', type: 'date', nullable: false, default: null },
      { name: 'mileage', type: 'integer', nullable: true, default: null },
      { name: 'maintenance_type', type: 'character varying(100)', nullable: false, default: null },
      { name: 'category', type: 'character varying(100)', nullable: false, default: null },
      { name: 'subcategory', type: 'character varying(100)', nullable: true, default: null },
      { name: 'description', type: 'text', nullable: false, default: null },
      { name: 'total_cost', type: 'numeric(10, 2)', nullable: false, default: null },
      { name: 'labor_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'parts_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'other_cost', type: 'numeric(10, 2)', nullable: true, default: null },
      { name: 'service_provider', type: 'character varying(255)', nullable: true, default: null },
      { name: 'service_provider_contact', type: 'character varying(255)', nullable: true, default: null },
      { name: 'service_provider_address', type: 'text', nullable: true, default: null },
      { name: 'warranty_period', type: 'integer', nullable: true, default: null },
      { name: 'warranty_expires', type: 'date', nullable: true, default: null },
      { name: 'warranty_notes', type: 'text', nullable: true, default: null },
      { name: 'is_scheduled_maintenance', type: 'boolean', nullable: true, default: 'false' },
      { name: 'next_maintenance_date', type: 'date', nullable: true, default: null },
      { name: 'next_maintenance_mileage', type: 'integer', nullable: true, default: null },
      { name: 'maintenance_interval', type: 'integer', nullable: true, default: null },
      { name: 'mileage_interval', type: 'integer', nullable: true, default: null },
      { name: 'parts_replaced', type: 'text[]', nullable: true, default: null },
      { name: 'parts_cost_breakdown', type: 'jsonb', nullable: true, default: null },
      { name: 'quality_rating', type: 'integer', nullable: true, default: null },
      { name: 'satisfaction_rating', type: 'integer', nullable: true, default: null },
      { name: 'issues_found', type: 'text[]', nullable: true, default: null },
      { name: 'recommendations', type: 'text[]', nullable: true, default: null },
      { name: 'photos', type: 'text[]', nullable: true, default: null },
      { name: 'receipts', type: 'text[]', nullable: true, default: null },
      { name: 'documents', type: 'text[]', nullable: true, default: null },
      { name: 'notes', type: 'text', nullable: true, default: null },
      { name: 'technician_notes', type: 'text', nullable: true, default: null },
      { name: 'status', type: 'character varying(50)', nullable: true, default: "'completed'" },
      { name: 'approved_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'approved_on', type: 'timestamp with time zone', nullable: true, default: null },
      { name: 'company_expense_id', type: 'text', nullable: true, default: null },
      { name: 'created_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'updated_by', type: 'character varying(255)', nullable: true, default: null },
      { name: 'created_at', type: 'timestamp with time zone', nullable: true, default: 'now()' },
      { name: 'updated_at', type: 'timestamp with time zone', nullable: true, default: 'now()' }
    ]
  }
  
  return fallbackColumns[tableName] || []
}
